### ISSUE TITLE
Create one-sheet: what the USFS is/isn't

### ISSUE THREAD

**Issue by jcmeloni-usds** [usds/us-forms-system#104]
We need a basic one-sheet for distribution to interested parties that describes:
* what the forms system is
* what the forms system isn't
* where to get more info
* how it's funded 
* how people can get involved

For publishing in: wiki, pdf, possibly printed but not a priority on the later

Please draft via branch and PR for review.

**Comment by jcmeloni-usds** [comment]
Assigning initially to @ju-liem and @fatimanoorva to:
* get this on the board
* prioritize
* assign as appropriate (j-mac I think you had started thinking about this?)

**Comment by jcmeloni-usds** [comment]
@fatima-gov Is this one of the things you're working on, or do we even need this anymore?

**Comment by fatima-gov** [comment]
I think most of this is somewhere on the wiki. At this time, I am more inclined to updating the wiki homepage to (1) include a brief "about the library" section and (2) a table to content linking to important sections within the wiki. In terms of hand-outs, we have the handy-dandy stack of info cards which also includes links to the wiki, how to subscribe to listserv and how to get in touch with us.

**Comment by jcmeloni-usds** [comment]
Fatima is right that all of this is in the wiki.  I updated some stuff and the hand-dandy stack of info cards should suffice.  Yay.
