### ISSUE TITLE
Create a USFS presentation deck 

### ISSUE THREAD

**Issue by jcmeloni-usds** [usds/us-forms-system#105]
This is very much related to #104 but in this case the target output would be a PPT that anyone on the team can use to present about the USFS.  Target a ~10min presentation.

Thoughts on scope (this is not prescriptive):
* what this is
* what this isn't
* how it started
* how it's used
* success examples
* how you can contribute

**Comment by jcmeloni-usds** [comment]
Assigning initially to @ju-liem and @fatimanoorva to:
* get this on the board
* prioritize
* assign as appropriate (j-mac I think you were already working on this?  also I'm sure anne has some stuff she's used)

**Comment by jcmeloni-usds** [comment]
@fatima-gov @bernars-usa What do you think about this -- still needed? (I think yes, but I also don't know if we have something made up yet)

**Comment by fatima-gov** [comment]
@jcmeloni-usds We added a link in the [README](https://github.com/usds/us-forms-system#more-project-artifacts) to the deck that jMac put together recently (which does cover a lot of USFS 101s). I do think it would be good to have a slightly updated version that is somewhat sharing-/printer-friendly (GIFs are great, but take up so much file size!). I will take this on!

**Comment by jcmeloni-usds** [comment]
Ok, I will make a new ticket for updating the deck.
