### ISSUE TITLE
Review and Update User Personas wiki page

### ISSUE THREAD

**Issue by jcmeloni-usds** [usds/us-forms-system#106]
In the early stages of this project, a user personas page (https://github.com/usds/us-forms-system/wiki/User-Personas-&-Scenarios-(Phase-1)) was created in the wiki. It is generally correct but we are missing the ties to this document throughout the wiki.   By this I mean that it's not clear why we created these personas and how they informed the work, or how people should use this page in the wiki.

Actions for this issue:
* review the informaton on the personas page
* update if necessary (probably more reorg and editing than factual updating -- but that's based on a quick glance)
* determine how this persona/scenario info is going to be used -- informative, referential, other?

**Comment by bernars-usa** [comment]
As I outlined in https://github.com/usds/us-forms-system/issues/203#issuecomment-412564895, I'm going to update the user personas this week in order to inform our next research phase.

**Comment by bernars-usa** [comment]
> - review the informaton on the personas page
> - update if necessary (probably more reorg and editing than factual updating -- but that's based on a quick glance)

I've updated the [User Personas](https://github.com/usds/us-forms-system/wiki/User-Personas-&-Scenarios) page on the wiki to reflect the two personas we're keeping in mind through our work: *developers* and *form owners*.  The information is mostly a distillation of what was there before, combining all developers into one persona, making minor updates to the developer persona based on what we've learned over the last couple of months, and removing references to "non-technical".

> - determine how this persona/scenario info is going to be used

I've added a brief description of how the personas are intended to be used at the beginning of the document. I've also reinforced this by linking to the personas in the following documents:

- New [User Interviews](https://github.com/usds/us-forms-system/wiki/User-Interviews) landing page
- [Research and Testing Strategy](https://github.com/usds/us-forms-system/wiki/Research-&-Testing-Strategy#what-is-necessary-to-make-a-usable-open-source-library-for-developers)
