### ISSUE TITLE
Rethink/rework "Existing Features" wiki page

### ISSUE THREAD

**Issue by jcmeloni-usds** [usds/us-forms-system#107]
We have a page called "Existing Features": https://github.com/usds/us-forms-system/wiki/Inventory-of-Existing-Features

I'm not sure these are all "features" so much as they are "components of the library".

I'd like us to take a look at this documentation again, and think about:
* does it match what a new user is looking for when they want to know what's in the library they can use
* is it organized in such a way that it makes sense to a user thinking about what's IN their form vs what's AROUND their form
* do the visual examples match up with the component type
* is the path to information complete, e.g. do the references in this page match up to the code for the component that the person might use (do we call something "foo" in this page but the code references it as "bar")

**Comment by jcmeloni-usds** [comment]
Assigning initially to @ju-liem and @fatimanoorva to:
* get this on the board
* prioritize
* assign as appropriate (@bernars-usa if this is already encompassed in the work you've been doing, my bad & sorry)

**Comment by bernars-usa** [comment]
> @bernars-usa if this is already encompassed in the work you've been doing, my bad & sorry

It's not on my list of work to be included in the PR(s) I have going right now, but this content is on my radar for another iteration. This is only to mitigate scope creep.

**Comment by jcmeloni-usds** [comment]
@bernars-usa great!

**Comment by fatimanoorva** [comment]
https://github.com/usds/us-forms-system/issues/138
