### ISSUE TITLE
Update research/testing strategy page

### ISSUE THREAD

**Issue by jcmeloni-usds** [usds/us-forms-system#109]
In the early stages of the project, a Research & Testing Strategy page was created: https://github.com/usds/us-forms-system/wiki/Research-&-Testing-Strategy

Please review and update as appropriate to reflect the following:
* the research that went into the creation of this project in the first place (and why we focused on what we did)
* the ways in which we gather and synthesize information from users in an ongoing fashion to address feature requests

Please ensure our documentation does not conflate work for the library with form creation best practices in general.

**Comment by jcmeloni-usds** [comment]
Assigning initially to @ju-liem and @fatimanoorva to:
* get this on the board
* prioritize
* assign as appropriate

**Comment by jcmeloni-usds** [comment]
@fatima-gov What do you think the status/quality of the content is at this point?

**Comment by fatima-gov** [comment]
@jcmeloni-usds I think this page is okay for now but will need to be updated as we firm up our research and testing plan for phase II (which can be a separate ticket).

> the research that went into the creation of this project in the first place (and why we focused on what we did)

I don't think the page as-is now is capturing this fully but may be that is something that belongs in a separate project 101/background page? I'd propose that we close this ticket but (1) make sure to include historical content in the one-pager https://github.com/usds/us-forms-system/issues/104 and (2) create a separate ticket to track phase II research planning and update this page accordingly.

**Comment by jcmeloni-usds** [comment]
I updated this wiki page w/ Fatima's plan :)
