### ISSUE TITLE
Create area in wiki for contributor call/status reports

### ISSUE THREAD

**Issue by jcmeloni-usds** [usds/us-forms-system#110]
Let's get into a cadence of reporting out progress against goals, as well as specific updates/changes in the repo/starter app, even if we don't have anyone besides us on the calls.

Strawperson template:
* call date/time
* attendees w/ affiliations
* report out against CAP Goals (bullet point updates)
* Major changes since last update
  * visual example if needed
* Known issues still around, or stuff broken by recent release (let's avoid that! :) )
* Q&A

**Comment by fatimanoorva** [comment]
one of my todo's for #111 :) will make sure to incorporate the above as well!

**Comment by jcmeloni-usds** [comment]
@fatimanoorva Great!  thanks.  If this is really a duplicate, feel free to close it as such. I was just trying to get things out of my head.

**Comment by fatimanoorva** [comment]
✅  Wiki pages updated accordingly.
