### ISSUE TITLE
Set up contributor call 

### ISSUE THREAD

**Issue by fatimanoorva** [usds/us-forms-system#111]
- [x] hold time on team's calendar (every other Thursday 2pm - 3pm)
- [x] set up biweekly contributor call starting week of July 26
- [x] finalize logistics (mailing lists, GSA web call formatting) 
- [x] update readme and wiki to include information on joining list and contributor calls
- [x] Define agenda (start each call with standup to give contributors an opportunity hear what we are working, address any open tickets from the community, Q&A time, etc _we will iterate this depending on how the community and call shape up_)

**Comment by annekainicUSDS** [comment]
@fatimanoorva First contributor call went great! I think for future calls we should limit them to 30 minutes. Right now we have a small audience, and reserving an hour on people's calendars is a lot to ask. I also worry about giving too much space on these calls to troubleshooting specific users' problems. It should be pretty high level, and more specific conversations should happen in tickets in the repo. What do you think to making future calls 30 minutes?
