### ISSUE TITLE
Refactor to remove VA code dependencies

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#113]
This is similar to #56 but on the code side. Many of the js/jsx files include dependencies from department-of-veterans-affairs, such as [SelectWidget.jsx](https://github.com/usds/us-forms-system/blob/28aa7a63763763e2b86284c05cc380e0677310b6/src/js/widgets/SelectWidget.jsx) which pulls in `asNumber` and [RadioWidget.js](https://github.com/usds/us-forms-system/blob/28aa7a63763763e2b86284c05cc380e0677310b6/src/js/widgets/RadioWidget.jsx) for `ExpandingGroup`. These should be refactored so that either 1) we have our own copy, 2) the VA site gets it from us-forms-system, or 3) both we and the VA site get it from some newly created component.

**Comment by jcmeloni-usds** [comment]
@dmethvin-gov Is this still a thing that's in the debt bucket, or has work progressed past this?  Thanks!

**Comment by dmethvin-gov** [comment]
Still here, this is due to our use of the forked `react-jsonschema-form` which will be addressed by #141 so I'll close this as a duplicate.
