### ISSUE TITLE
Overly specific usa-date-of-birth classname in DateWidget?

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#115]
The DateWidget has a [classname of `usa-date-of-birth`](https://github.com/usds/us-forms-system/blob/28aa7a63763763e2b86284c05cc380e0677310b6/src/js/widgets/DateWidget.jsx#L81) which seems overly specific since this could be used for other dates. The widget [does limit the year to the range 1900-3000](https://github.com/usds/us-forms-system/blob/28aa7a63763763e2b86284c05cc380e0677310b6/src/js/widgets/DateWidget.jsx#L112-L113) which is probably fine for birth dates but may not always be appropriate in forms that require historical dates, e.g. *"What date was this building constructed?"* on a register of historic places.

Given the name of the widget it seems like ensuring it can be used in a generic way is the best course of action, but there may be other approaches.

**Comment by dmethvin-gov** [comment]
OK, I gather this excess specificity is [inherited from USWDS](https://github.com/uswds/uswds/blob/20e266321fe67c65bb96007006a3a9d6d77c4f80/src/stylesheets/elements/_inputs.scss#L341-L344). If people agree that it should be more generic I can open a ticket there.

**Comment by jcmeloni-usds** [comment]
@dmethvin-gov If this is still a thing, and what is now called usa-date-of-birth can be used for other dates not just date of birth, then from a product perspective it should be generic.

**Comment by dmethvin-gov** [comment]
I opened https://github.com/uswds/uswds/issues/2805 since it's a USWDS issue. Looks like they renamed it in V2 so we could fix it when we upgrade.

**Comment by dmethvin-gov** [comment]
Since we already have several tickets related to USWDS 2.0 I'll close this one; we can tackle them all at once in the upgrade. Note that the [USWDS 2.0 advice has changed](https://v2.designsystem.digital.gov/components/form-controls/#date-input) and they now recommend three text fields rather than dropdowns for month and day. (I agree with this advice as well.)
