### ISSUE TITLE
SelectWidget doesn't handle select-multiple correctly

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#116]
On blur or change, the widget [gets the value of the select](https://github.com/usds/us-forms-system/blob/28aa7a63763763e2b86284c05cc380e0677310b6/src/js/widgets/SelectWidget.jsx#L48) but [uses the `value` property](https://github.com/usds/us-forms-system/blob/28aa7a63763763e2b86284c05cc380e0677310b6/src/js/widgets/SelectWidget.jsx#L14-L16) which [isn't correct](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement) for a select-multiple element. The correct general solution is to iterate through `select.options` and return an array of the `selected` ones. There is [a `selectedOptions` property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedOptions) but it's not supported by IE11.

We'll need to fix this and add a test case.

**Comment by jcmeloni-usds** [comment]
@dmethvin-gov Cofirming this is still an issue, and if so, yes, let's fix it at some point.
