### ISSUE TITLE
Unexpected border-radius change

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#126]
Sometimes certain elements suddenly get a border radius. It seems to be when they are in a `:focus` or `:hover` state.

Examples I've found so far:
1. Dropdowns
<img width="540" alt="screen shot 2018-06-30 at 6 32 35 pm" src="https://user-images.githubusercontent.com/25183456/42129524-a3151c62-7c94-11e8-9eeb-abf5b88849a9.png">

2. Expandable group buttons
<img width="679" alt="screen shot 2018-06-30 at 6 37 10 pm" src="https://user-images.githubusercontent.com/25183456/42129525-a69e9f70-7c94-11e8-859e-84d57d6e2b52.png">

This is likely a CSS issue.

**Comment by dmethvin-gov** [comment]
What version are you using? When I build the starter app from the current master it doesn't show any rounded corners on selects. The current master [seems to have the right styles](https://github.com/usds/us-forms-system/blob/9638ac4e45c257aa6deb6a7443f4c214e6851892/lib/css/styles.css#L2721-L2726). If I remove the `border-radius: 0` there the rounded corners do come back. Strange that the rounding would stay but the default selection arrow is gone.

**Comment by annekainicUSDS** [comment]
@dmethvin-gov I'm pulling from master as well for the starter app and am seeing the rounded borders. It's very hard to see on the review page, but there's a slight border-radius of 5px that is applied, which for some reason is only visible on `:hover`.

<img width="161" alt="screen shot 2018-07-02 at 2 51 48 pm" src="https://user-images.githubusercontent.com/25183456/42181522-22b5db62-7e09-11e8-9b3f-db2af472936a.png">

<img width="561" alt="screen shot 2018-07-02 at 3 03 34 pm" src="https://user-images.githubusercontent.com/25183456/42181538-26f8b992-7e09-11e8-86c7-ab4a0c5a04d1.png">

I've traced it to [this part of our stylesheets](https://github.com/usds/us-forms-system/blob/master/src/scss/modules/_m-schemaform.scss#L624), which was added in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/7218/files#diff-91c7dd17f79d9999ebb1e34e2a3bc7a8R572). I think it was a mistake because it's also happening on Vets.gov right now. I think it's just too broad of a selector, and was meant to apply to regular buttons nested within a review panel.

Here's how it looks now:
<img width="326" alt="screen shot 2018-07-02 at 3 06 16 pm" src="https://user-images.githubusercontent.com/25183456/42181667-971f6d7e-7e09-11e8-8c06-cdb9273663db.png">

Here's how it looks if I remove the style entirely:
<img width="535" alt="screen shot 2018-07-02 at 3 06 03 pm" src="https://user-images.githubusercontent.com/25183456/42181673-9e1ed0ce-7e09-11e8-8539-a938858b3a69.png">

See the effect on the nested button within? I'm going to update the selector to not apply to the panel headers.

Haven't investigated the other case yet, but will look at that next!
