### ISSUE TITLE
Remove dependency on vets-json-schema for unit tests

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#127]
Right now our unit tests load Vets.gov schema (vets-json-schema) in order to run our unit tests. Remove and replace with possibly something more generic?

**Comment by dmethvin-gov** [comment]
Yes! I'm not sure at the moment how well covered our code base is anyway, it seems likely that the vets schema is only a subset of what the library can do. Also I've seen spelling errors [like this one](https://github.com/usds/us-forms-system/blob/9638ac4e45c257aa6deb6a7443f4c214e6851892/test/js/review/SubmitController.unit.spec.jsx#L310) and I'm not sure if they're just cosmetic or should have affected the results.

**Comment by annekainicUSDS** [comment]
The reason we're needing to import `vets-json-schema` right now is because this repo lacks the schema necessary for many of the definitions to properly render, as described in [this ticket](https://github.com/usds/us-forms-system/issues/125). So this will be solved once we figure out what the right way to handle the schema for definitions will be.

**Comment by ju-liem** [comment]
This will be further discussed after a direction is decided in issue #125
