### ISSUE TITLE
Technical docs for how to build a form

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#128]
Separate from the docs we have already, which are more detailed descriptions of the specific fields/widgets, etc., is there enough information for someone to understand the steps to building a form? A tutorial or recipe for different patterns, etc.

**Comment by dmethvin-gov** [comment]
For background, the reasoning behind this is driven by a scenario like the upcoming hackathon where people are unlikely to enter via the top of the docs tree. We'd like to get them to success quickly by having them focus on the form.js file and the essential knowledge they'll need in order to build that. A lot of it can be accomplished via copy/paste until they reach the more complex customization scenarios.

**Comment by bernars-usa** [comment]
This is definitely a gap in the current docs. The idea of "[Creating a form config file](https://github.com/usds/us-forms-system/blob/creating-forms/docs/building-a-form/creating-a-form-config-file.md)" and "[Common patterns for building a form](https://github.com/usds/us-forms-system/blob/creating-forms/docs/building-a-form/common-patterns-for-building-forms.md)" was to have the basic "Setting up your config file" and then "Customizing your config file" docs. What should be expanded on in those as far as you all can tell?

**Comment by bernars-usa** [comment]
Also linking up #137 here, which @dmethvin-gov opened this morning. ✨

**Comment by bernars-usa** [comment]
> We'd like to get them to success quickly by having them focus on the form.js file and the essential knowledge they'll need in order to build that. A lot of it can be accomplished via copy/paste until they reach the more complex customization scenarios.

Does this feel adequately addressed with #149 for now?

**Comment by annekainicUSDS** [comment]
I think this ticket is complete to improving the docs we currently have. I still think we should explore creating a tutorial, similar to what [the React tutorial](https://reactjs.org/tutorial/tutorial.html) does. I created a separate ticket to explore that specifically: https://github.com/usds/us-forms-system/issues/191. Going to close this one in the meantime.
