### ISSUE TITLE
Remove federal law language in SubmitController

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#129]
There's language in the `SubmitController` component that refers to federal law. This should probably be removed, and that language should be added separately for specific apps that need it.

**Comment by dmethvin-gov** [comment]
As discussed with Anne today, this text is on the review page. We could add a separate React component to contain arbitrary HTML that goes above the submit button, use a field in the forms.js schema to define text, or perhaps both? 

For the "both" case I'm thinking we have a simple default "text above the submit button" React component that draws its text from the form definition. If someone needs a more robust set of content they can replace the React component but most people will be able to just define the text. 

Perhaps we could use that same approach and component with other text as well, such as the Introduction? That way we get convenience for the simple case (they're already editing the form.js file) but flexibility for more complex cases. It's also more generic so we don't end up creating essentially identical "Introduction", "BeforeSubmitButton", etc. components each time we find that we need text to be somewhere.

**Comment by dmethvin-gov** [comment]
Fixed by #209 and #242.
