### ISSUE TITLE
Document the ability to track form stats and errors via Google Analytics

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#134]
It's in there but there's no docs that I can see about what is reported.

**Comment by dmethvin-gov** [comment]
Added Sentry (sentry.io via the include of the raven-js package), not sure how that's configured or whether it should stay.

**Comment by bernars-usa** [comment]
There's definitely a need for some more content around search engine analytics in general. Are there best practices we want to note? It's probably not a good idea to release a web form without analytics hooks, even if they're very basic for tracking pageviews.
