### ISSUE TITLE
Quick-start documentation (focused on hackfest)

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#137]
# INITIAL SETUP

Assume folder and project name below is "awesome-form"

* On GitHub, create a new empty repo "awesome-form"
  - We'll push files from the cloned repo so no need to add anything now
  - Note the clone URL, something like this:
    `https://github.com/YOURACCOUNT/awesome-form.git`
* Go to the command line
* `git clone https://github.com/usds/us-forms-system-starter-app.git awesome-form`
  - This clones into the awesome-form directory under the current directory
* Change to the new project directory
* Edit package.json
  - name: "awesome-form"
  - version: "0.0.1"
  - description: "Awesome form based on us-forms-system"
  - repository.url: Use the URL GitHub gave you in this format
    `git+https://github.com/YOURNAME/awesome-form.git`
* `git remote rename origin starter-app`
* `git remote add origin https://github.com/YOURACCOUNT/awesome-form.git`
* `npm install`
* `npm start`
* In a browser, go to http://localhost:8080
  - You should see the sample form rendered
* Back to the command line, press Ctrl+C to stop the dev server
* `git add package.json package-lock.json`
* `git commit -m "Start of my awesome form"`
* `git push origin`

# CHANGE THE SAMPLE FORM

TK - need a quick "catalog" of visual components and how they would be integrated into the project via settings in forms.js

**Comment by bernars-usa** [comment]
This was super helpful, thanks, @dmethvin-gov!

**Comment by dmethvin-gov** [comment]
This info is now incorporated [into the docs](https://github.com/usds/us-forms-system/blob/cced5198714b0eb57dbdc1caf0d38dd4d20108c7/docs/getting-started/creating-a-new-application-with-the-us-forms-system-starter-app.md) so I'll close this ticket.
