### ISSUE TITLE
"About the US Forms System library" needs reorganization

### ISSUE THREAD

**Issue by bernars-usa** [usds/us-forms-system#139]
This topic has thus far been pared down quite a bit from what existed originally, but it's by no means optimal. I'm waiting for mind mapping software, which will allow a few of us to look at what's there and quickly iterate on better organization. It's possible some of the content needs to be pulled out into separate topics altogether.

**Comment by bernars-usa** [comment]
#167 has been merged, and there are a couple of outstanding comments from that work (listed at the bottom of the PR). The largest one, and the one I'm most concerned about, is figuring out this set of comments between myself and @annekainicUSDS: https://github.com/usds/us-forms-system/pull/167#discussion_r203396002. I'd love some help talking through what should go where, and what those topics should be called.

**Comment by annekainicUSDS** [comment]
This has been completed by this PR: https://github.com/usds/us-forms-system/pull/186
