### ISSUE TITLE
`transformForSubmit` strips non-empty `showPagePerItem` pages

### ISSUE THREAD

**Issue by markgreenburg** [usds/us-forms-system#140]
**What Happens**
`transformForSubmit` filters out data from active pages when the properties of those pages match properties in schemas of other inactive pages - even though properties are required to match across these pages due to them having been created with `showPagePerItem` using the common property as the `arrayPath`.

**How to Reproduce**
1. Set up a form page with an array schema definition:
```
disabilities: {
  type: 'array',
  maxItems: 100,
  items: {
    type: 'object',
    properties: {...}
  }
}
```
2. Set up two other pages using `showPagePerItem`, with the original page as the `arrayPath`:
```
evidenceType: {
  path: 'supporting-evidence/:index/evidence-type',
  showPagePerItem: true,
  itemFilter: (item) => _.get('view:selected', item),
  arrayPath: 'disabilities',
  uiSchema: {...},
  schema: {
    type: 'object',
    properties: {
      disabilities: {...}
      ...
    }
  }
},
vaMedicalRecordsIntro: {
  path: 'supporting-evidence/:index/va-medical-records-intro',
  showPagePerItem: true,
  itemFilter: (item) => _.get('view:selected', item),
  arrayPath: 'disabilities',
  uiSchema: {...},
  schema: {
    type: 'object',
    properties: {
      disabilities: {...}
      ...
    }
  }
}
```
3. Fill out the form such that at least one of the two child pages is 'inactive'
4. Transform data using transformForSubmit:
```
const formConfig = {
  ...
  transformForSubmit
  ...
};
```
Result:
formData that's returned from `transformForSubmit` lacks a `disabilities` property

Why?
`us-forms-system/src/js/helpers.js`
The problem happens within `transformForSubmit`:
- transformForSubmit calls `getInactivePages`, which will put all inactive pages into an array
- then `filterInactivePages(pages, form)` gets called with this inactive page list
- One of the inactive pages will have `disabilities` as a property
- `disabilities` will be stripped from the form data
- This happens despite the fact that some other active pages have a `disabilities` property with data on it

**Expected behavior**
Properties on inactive pages are not stripped if they're also found in active pages.

**Possible Solution**
- Keep a list of properties belonging to active pages
- Check the properties getting removed against the list of properties known to belong to active pages
- Only remove a property from form data if its page is inactive AND it's not on the list of active page properties.

**Additional context**
- vets.gov Form 526 can't submit form data without this bug getting addressed. This is blocking integration testing for us.

**Comment by annekainicUSDS** [comment]
Working on recreating this issue. The Vets.gov team is not completely blocked for now; they've implemented a temporary workaround in their own codebase.

**Comment by annekainicUSDS** [comment]
PR to resolve this issue is open: https://github.com/usds/us-forms-system/pull/155

**Comment by markgreenburg** [comment]
Thanks Anne! Yep, was able to test out your PR locally and the issue seems to be resolved, using the same data with which we were previously having trouble.
