### ISSUE TITLE
Look into release-drafter for making release notes

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#144]
One less thing to deal with. I've never used it but it looks interesting.

https://github.com/toolmantim/release-drafter

**Comment by annekainicUSDS** [comment]
@bernars-usa Looks like @dmethvin-gov made this ticket awhile ago for release notes ideas. Curious on your thoughts on this!

**Comment by dmethvin-gov** [comment]
Yeah, I stumbled back across it this morning. I suspect that to use this effectively we need to squash commits down (which we're now enforcing in the GitHub UI) and also mention tickets (issues and PRs) explicitly. Both seem like good ideas anyway. Since it's a draft we can do whatever we want with the result so we're not limited to the way it looks. Once this most recent release is out I can turn it on and we can see what it does for us.

**Comment by bernars-usa** [comment]
Yeah, that tool would be really nice for simply creating the list of issues and PRs to mention in the release. Release notes are made much better by a human touch, summarizing both the problem and how it was solved. It seems the tool is depending on well-written issue and PR titles, which is fine for us to use as a jumping off point, but not the silver bullet for public consumption.

**Comment by jcmeloni-usds** [comment]
Agree; anything that gets a starting point and is easy is great, but we should always touch them up before releasing for public consumption (you can assign final looks to me for review/updates).  Given that, what do you want to do here?

**Comment by dmethvin-gov** [comment]
@bernars-usa Created a template for us and I'm fine with using that. We can close this for now if you want.

**Comment by bernars-usa** [comment]
Agreed, I'd recommend using the template for now. It's entirely possible that down the line, releases include so much that a tool like release-drafter might help a lot, but not right now.
