### ISSUE TITLE
Add link checker to CI

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#145]
Per #143 I think we should be able to add https://github.com/tcort/markdown-link-check pretty easily. Rather than make it part of `npm run build` I'm inclined to just make it part of the CI for PRs and merges to master. When #97 is resolved we'll have a commit hook that runs build to ensure that all the built files are in sync with the source, and I'm concerned that checking all the links on each build would take too long.

**Comment by jcmeloni-usds** [comment]
@dmethvin-gov Still a thing, or no?

**Comment by dmethvin-gov** [comment]
Yes, still a thing. If this takes quite a bit of time (it may if we scan all Markdown files) we'd only do this sporadically to avoid the extra work on every commit.
