### ISSUE TITLE
Consider making introduction page a standard form page

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#150]
There are [several bits of special-case code](https://github.com/usds/us-forms-system/search?q=introduction) related to handling the introduction page. There is also an implicit assumption that the route name for the page is "/introduction". 

What if we just let people define form pages that could have only text (via a React component) and a "Continue" button? That allows not only a first-page introduction but interstitial help/continuation pages to introduce new chapters, and they can have any route name they want.

Related to https://github.com/usds/us-forms-system-starter-app/issues/14 .

**Comment by jcmeloni-usds** [comment]
@dmethvin-gov Did this get resolved to y'all's satisfaction in subsequent issues/PRs?

**Comment by jcmeloni-usds** [comment]
Moved to phase 2.

**Comment by dmethvin-gov** [comment]
This ticket is blocked by #257
