### ISSUE TITLE
Explore pulling out definitions

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#164]
The definitions that are included in the library are designed to help users more quickly and succinctly fill out pieces of the form config. For questions that might be frequently asked, such as full name and address, we've provided definitions for those so they can be popped into the config and reused as much times as needed. You can think about the code that definitions include as chunks of the config extracted out into a separate file to be reused wherever needed.

There are 2 problems with using definitions now:
1. They mainly only contain `uiSchema`, not the actual `schema`, which means they are not sufficient themselves to properly render a field. Just popping `fullName.js` into your form config is not going to properly render the name fields.
2. They make assumptions about the way you ask certain questions. They were designed originally only for Vets.gov's uses, so they contain information about the way we ask those questions on Vets.gov. For example, whenever we ask for someone's name, we include the following fields: first, middle, last, and suffix. The definition `fullName.js` includes `uiSchema` for these 4 fields. It's possible a user of this library might not want to include a suffix field, in which case the definition for full name would be unusable for them.

In general I think we should think about the way we include helpful chunks of code for common questions to make building a basic form faster and easier, but for now I think the definitions are not useful to new users of the library. I suggest we consider pulling them out of the library and back into Vets.gov for their own specific uses, and we consider ways to include helpers for common questions as a separate issue.

Thoughts @dmethvin-gov?

**Comment by dmethvin-gov** [comment]
Yep, I think we should leave them out and encourage people to build things from basics for now. This is a case where leaving them out doesn't hurt vets.gov since they can have their own copies, so that's good as well.

**Comment by annekainicUSDS** [comment]
As I looked into the work involved here, it's a bit more complicated than just pulling out the files under `src/js/definitions`. The definitions use validation functions to specific types of fields (e.g., `ssn`, `autosuggest`, etc.), helpers, utilities, etc. Some of those validations and helpers might be useful to still retain in the library, but I think we need to do a more thorough review of which ones have pieces that could remain in the library, and, if so, how do we document their use. I think the first step here is to do an inventory of definitions and what they use. I'll document that in this ticket.

**Comment by annekainicUSDS** [comment]
| Definitions  | Validation  | Other utilities  | Extract?  |
|---|---|---|---|
| address  | some validation functions contained w/in definitions file  | options for cities/states and more validation functions  | x  |
| autosuggest  | yes  | no  | This might be generally useful, don't extract yet  |
| bankAccount  | yes  | no  | x  |
| currency  | no  | no  | This might be generally useful, don't extract yet  |
| currentOrPastDate  | yes  | no  |   |
| currentOrPastMonthYear  | yes  | yes, lodash and another definition file  |   |
| date  | yes  | no  |   |
| dateRange  | yes  | imports date definition  |   |
| file  | yes  | no  | x  |
| fullName  | no  | no  | x  |
| monthYear  | yes  | no  | This sets the `monthYear` option, which helps with review formatting, so figure out way to document this before extracting  |
| monthYearRange  | yes  | no  |   |
| nonRequiredFullName  | no  | lodash  | x  |
| personId  | no  | lodash  | x  |
| phone  | no  | widgets and review widgets  | this uiSchema passes in some useful classes and widgets, so figure out best way to extract this  |
| ssn  | yes  | widgets and review widgets  | also passes some classes and widgets, figure out best way to extract this  |
| year  | yes  | review widget  |   |

**Comment by bernars-usa** [comment]
Does "x" mean extract?

**Comment by dmethvin-gov** [comment]
Does "extract" mean "remove from the library"?

**Comment by annekainicUSDS** [comment]
Yes, extract means remove from the library, and x means extract. I want to do this in chunks of work because while I'm pulling stuff out of USFS, I'm putting stuff back into vets-website, updating paths, and making sure everything works. I'm starting with the ones that definitely need to be pulled out because they are so specific to a certain type of data structure, and will tackle the rest separately.

**Comment by annekainicUSDS** [comment]
We've decided for the ones we're not extracting for now to add the schemas into the definitions so that they are complete. Tackling that in a separate PR.
