### ISSUE TITLE
Handling different navigation/form progress designs

### ISSUE THREAD

**Issue by afeld** [usds/us-forms-system#169]
Hello! I'm at @18F, and part of the team working on [the new form for eQIP](https://github.com/18F/e-QIP-prototype). We are interested in trying out the Forms System! eQIP is a relatively large+complex React frontend already, so not sure how easy realistic switching over will be from a code perspective...

That being said, I see in the [starter app](https://github.com/usds/us-forms-system-starter-app) that there are some interface elements included that aren't explicitly part of [the specification](https://github.com/usds/us-forms-system-starter-app/blob/master/js/config/form.js), namely the progress bar, page numbers, and navigation buttons at the bottom.

![screen shot 2018-07-17 at 10 03 24 pm](https://user-images.githubusercontent.com/86842/42855178-46a59e58-8a0d-11e8-9112-a3efa44ea773.png)

In our app, we have a hierarchical navigational structure with conditional styling, etc. To give you an idea:

![screen recording 2018-06-28 at 02 11 pm](https://user-images.githubusercontent.com/86842/42052670-6f2e4f9e-7add-11e8-9ff7-2e3a1575e860.gif)

<img width="653" alt="42545041-35a518f2-846a-11e8-9eab-b8540e0310be" src="https://user-images.githubusercontent.com/86842/42855782-22a7de5a-8a10-11e8-84ae-b542dcd9000a.png">

**From an _interface_ perspective, any guesses about how hard it would be to leverage the Forms System?** Rather than try to switch the whole form over at once, it would be great to try it out more piecemeal. Perhaps there are lower-level components we can leverage?

I know this is a big question, so feel free to point me to existing documentation/issues. Also more than happy to set up a time to talk through things and see if we can be guinea pigs for the project (aidan.feldman@gsa.gov). Thanks!

**Comment by dmethvin-gov** [comment]
Thanks for the feedback @afeld! Use cases like this are exactly what we need to determine the next steps for this project. 

As you've noted, the idea of chapters, pages, and the nav comes from us-forms-system. Some form elements are taken from react-json-schema and others are new widgets in us-forms-system. You can see those in [`/src/widgets`](https://github.com/usds/us-forms-system/tree/master/src/js/widgets).

At the moment I think the project is too monolithic to be oriented for use cases like this but it seems like we could do it. The `formConfig` defines everything in one big object (chapters, pages, form appearance, transformation escape hatches, output schema) and it's passed around liberally. However, most widgets have a small number of dependencies, mostly on React or other widgets. Perhaps we could break out the widgets into a different repo that is independent of the nav?

In the meantime you could try pulling out some of the widgets to see whether they work standalone and if they do the trick for your use case. If so, that could make a stronger case for having the widgets separated from the nav and exposed as a project to themselves.

**Comment by afeld** [comment]
Yeah, a couple ways I could see for using the System more incrementally:

* Try specifying the individual pages as their own forms, so navigating would instantiate a new "form" in the Forms System sense
* Use the underlying widget components directly, as you suggested

Will poke around, but any other guidance is certainly welcome!

**Comment by dmethvin-gov** [comment]
I was thinking about something similar last night. One data structure could define the chapter/page hierarchy, one could define which widgets go on a particular page and their relation to the output schema, and another map widgets to actual code implementation. For the case of Bring Your Own Navigation you would just want the page definition and widget-to-code setup. Right now we have a single deeply nested `formConfig` doing all of that and it directly references React components in some cases. With the right encapsulation it should be possible to write a widget implementation in other frameworks or even plain JS but keep the data structures the same.

**Comment by jcmeloni-usds** [comment]
Just an update here -- as we determine precisely what 2.0.0-alpha might look like (starting Oct 1, aka "phase 2") this is something that will be top of mind  It's important for the library to be generic and broadly useful, and not being prescriptive about a lot of things.  Right now we're still pretty prescriptive in some cases.  That works for some, doesn't work for others.  We want to fix that!

**Comment by annekainicUSDS** [comment]
Duplicate ticket here: https://github.com/usds/us-forms-system/issues/201

**Comment by easherma** [comment]
#66 also related

**Comment by dmethvin-gov** [comment]
For now this library is committed to the wizard-style design that provides forward, back, and a review page.
