### ISSUE TITLE
Provide documentation around what is/what is not included in the library re: data persistence

### ISSUE THREAD

**Issue by afeld** [usds/us-forms-system#171]
In the documentation and examples, I didn't see any recommendations around how to handle persistence, or even retrieval of the form data. Haven't actually poked around at the code to try and retrieve it, but any tips that could be added to the docs?

**Comment by afeld** [comment]
Ah! Now seeing the mention of Redux in [the documentation](https://github.com/usds/us-forms-system/blob/master/docs/building-a-form/about-the-us-forms-system-library.md#how-us-forms-system-uses-rjsf), and the state structure in the [starter app](https://github.com/usds/us-forms-system-starter-app):

<img width="841" alt="screen shot 2018-07-17 at 10 48 36 pm" src="https://user-images.githubusercontent.com/86842/42856581-d6f3efa4-8a13-11e8-8671-ec05f4f1dbf3.png">

That might be a good thing to elaborate on in the docs, and then maybe just reference other documentation around how to persist data from Redux generally.

**Comment by afeld** [comment]
Was also looking at [Redux Form](https://redux-form.com/) - curious how much overlap that has here.

**Comment by annekainicUSDS** [comment]
Hi @afeld, thanks for this feedback! I agree, our docs could be more explicit about how we're using Redux. We're actively working on reorganizing and improving our docs right now, so this would be a good thing to include in that work. I will add this to our project board to keep track of.

**Comment by jcmeloni-usds** [comment]
I failed to write anything about this.  It would be worth writing a brief entry in the library docs itself, maybe a paragraph or so, about current state and potential future state.

**Comment by annekainicUSDS** [comment]
Add a link in our docs of the VA's implementation of retrieving form data with a brief description of how it works.

**Comment by dmethvin-gov** [comment]
The VA pages wrap the form with [RoutedSavableApp](https://github.com/department-of-veterans-affairs/vets-website/blob/8042318adfb2130caebc9771373f4ab936e16784/src/platform/forms/save-in-progress/RoutedSavableApp.jsx) which provides data persistence and things like the "Are you sure you want to leave?" prompt if they try to navigate away from the page.
