### ISSUE TITLE
Hidden contextual information: Import component from the VA design system

### ISSUE THREAD

**Issue by bernars-usa** [usds/us-forms-system#173]
From @annekainicUSDS's comment in https://github.com/usds/us-forms-system/pull/163#issuecomment-405604300:

> Hidden contextual information: this requires importing a component from the VA design system, so I'm not sure how we should include documentation on this. Eventually we may want to copy the needed components for this functionality into us-forms-system.

In the meantime, I'll remove the documentation about it, unless there's another solution.

**Comment by dmethvin-gov** [comment]
Talking with @fatimanoorva it looks to me as if this is already done. The [ExpandingGroup.jsx file](https://github.com/usds/us-forms-system/blob/807d26b9a0b44b3767ddf5708c43fd5367a8d473/src/js/components/ExpandingGroup.jsx) is here in this repo. It's used to implement the `'ui:options': 'expandUnder'` functionality (we even used it in the hackfest forms) so the code has to stay. Close this ticket?

**Comment by bernars-usa** [comment]
If it does exist, we need to add back the docs that were removed in https://github.com/usds/us-forms-system/commit/a959b49a99bdedc3bd7a55cc4e7f730221d4752e.

**Comment by dmethvin-gov** [comment]
I think this particular piece of code is only supposed to be accessed by form creators via `ui:options` so it doesn't need to be documented as a code component. At least that was my understanding from what I'm reading.

**Comment by annekainicUSDS** [comment]
I don't think `ExpandingGroup` completely covers this functionality. All `ExpandingGroup` does is expand some nested content, with a transition. The styling of the hidden contextual information, pictured [here](https://raw.githubusercontent.com/wiki/usds/us-forms-system/images/Contextual-info-hidden.jpg), is still a specific component that lives within VA's design system: https://github.com/department-of-veterans-affairs/design-system/blob/master/src/components/AdditionalInfo/AdditionalInfo.jsx. We would still need to import this into USFS.

**Comment by jcmeloni-usds** [comment]
@annekainicUSDS Confirming this is still a to-do -- based on your comment that's what it seems.

**Comment by jcmeloni-usds** [comment]
Dave confirmed that expand-under stuff does work in the 1.x-stable and so we'll call this good.  

If the request is actually for something different, and that feature is useful broadly (beyond just VA use cases), team should consider that a new feature request for phase 2 and prioritize / do / document accordingly.
