### ISSUE TITLE
Cross-link between conceptual content and reference content about widgets and components

### ISSUE THREAD

**Issue by bernars-usa** [usds/us-forms-system#178]
There are mentions of widget and component usage around the docs, and there are now reference docs about those widgets and components. It would be great to bring those closer together by cross-linking.

This came up in a discussion between @dmethvin-gov and @annekainicUSDS in https://github.com/usds/us-forms-system/pull/174#discussion_r203715156.

**Comment by bernars-usa** [comment]
Along with this work, I'm also going to divide the widgets and definitions into two separate topics. We discussed this in https://github.com/usds/us-forms-system/pull/167#discussion_r203390197.

**Comment by annekainicUSDS** [comment]
I think this has been complete with https://github.com/usds/us-forms-system/pull/182 and https://github.com/usds/us-forms-system/pull/184. @bernars-usa can you confirm that we can close this ticket?

**Comment by bernars-usa** [comment]
Yes! This is complete.
