### ISSUE TITLE
Clarify description of `keepInPageOnReview` property

### ISSUE THREAD

**Issue by bernars-usa** [usds/us-forms-system#180]
@annekainicUSDS and I worked through a description of the `keepInPageOnReview` property in https://github.com/usds/us-forms-system/pull/175#discussion_r203760818. Now that it's pretty well settled, that description should be added to the usage guidelines for review pages (https://github.com/usds/us-forms-system/blob/master/docs/building-a-form/available-form-features-and-usage-guidelines.md#usage-guidelines-13). I think a straight up copy-paste is best here, since the original text is in a code comment.

**Comment by jcmeloni-usds** [comment]
@bernars-usa Still a thing that needs to be copy-pasted?

**Comment by bernars-usa** [comment]
Nope, the blame seems to show I added this description at some point not long after alongside a bunch of other revisions. Closing!
