### ISSUE TITLE
7/25 Forms Hackathon Information

### ISSUE THREAD

**Issue by fatima-gov** [usds/us-forms-system#190]
# US Forms Hackathon Information

Thanks for participating in the first US Forms Hackathon! Here’s some information about the event:

1. **Find a team! We'd like you to pair up.**
  - If you have frontend experience, especially with Javascript, then find someone with less of that experience, and vice-versa.
  - There are some designers around! They're great for helping think through tricky UX problems. Flag them down if you need them!

2. **Install the starter app and set up your repo**:  (https://github.com/usds/us-forms-system/blob/master/docs/getting-started/creating-a-new-application-with-the-us-forms-system-starter-app.md)
  a. Use a new public repo under your username.
  b. In the repo description, add the name of the form you're building.
  c. Start building your form!

3. **Challenge Part 1 | Warm up**: Build USCIS Form G-1145
  - https://www.uscis.gov/g-1145

4. **Challenge Part 2 | Main event**: Choose one of the two below forms to build.
  - IRS Form 4506 T: https://www.irs.gov/pub/irs-pdf/f4506t.pdf
  - SSA Application for a Social Security Card: https://www.ssa.gov/forms/ss-5.pdf

5. **Demos and feedback start at 7:00. Please be prepared to**:
  - Give a < 5 minute demo of your experience building a form.
  - Talk about what went well.
  - Talk about things that didn't go well.
  - Please take few minutes to complete share your feedback here: https://usfs.typeform.com/to/FVxm1L

**Comment by kaschm-usds** [comment]
Feedback from me: 

- A little circuitous to find the Starter app page: [Repo Page](https://github.com/usds/us-forms-system) --> "Using the Libary" Section: [Starter App](https://github.com/usds/us-forms-system-starter-app) --> Scroll all the way to bottom, click '[Documentation](https://github.com/usds/us-forms-system/tree/master/docs#us-forms-system-documentation)' --> Clicked '[Getting Started](https://github.com/usds/us-forms-system/blob/master/docs/getting-started/README.md)' 
- Not clear that installing the starter app will install all the required tools (react, node)
-

**Comment by annekainicUSDS** [comment]
Clarify the difference between imported files coming from the `lib/` directory and the original source files from `src/`, which are probably more readable, and are what we link to throughout our documentation.

**Comment by annekainicUSDS** [comment]
Make more clear in the docs on `schema` and `uiSchema` how both are used. There was some confusion in the description of how `uiSchema` was developed by rjsf if that meant that rjsf only uses `uiSchmea` and not the regular `schema`. Make clear that both are used by rjsf, and by consequence, our library, and that they serve different purposes.

**Comment by dmethvin-gov** [comment]
The [Quick Start `form.js`](https://github.com/usds/us-forms-system/blob/master/docs/building-a-form/quick-start-example-formjs-file.md) is more of an "every feature in the system" example. We need a simple progression example that shows a true simple config file.

**Comment by dmethvin-gov** [comment]
In definitions like https://github.com/usds/us-forms-system/blob/master/docs/building-a-form/common-definitions.md#phone you actually also need corresponding `schema` definitions to match up with the `uiSchema` defined here. In this case, the `uiSchema` defines an error message that must be defined the `schema` so that it gives a correct error message. This is most likely true of several others.

**Comment by annekainicUSDS** [comment]
Include guidance on where chunks of `uiSchema` and `schema` live. Definitions are part of that, but perhaps there's more information we can include about this.

**Comment by annekainicUSDS** [comment]
Make available components highly visible and easily browsable. Right now it's kind of difficult to know what components are available and what they do and look like. Could be something similar to how USWDS inventories their components, with left navigation and lots of visuals and code samples.

**Comment by annekainicUSDS** [comment]
Getting started docs are too complicated, wasn't sure where to look first and was overwhelmed by information.

**Comment by annekainicUSDS** [comment]
Beef up instructions on incorporating library into existing repo.

**Comment by annekainicUSDS** [comment]
Unclear how 'ui:errorMessages' property matches the schema properties (e.g., pattern, minLength, etc.).

**Comment by annekainicUSDS** [comment]
Create docs on how the review page works.

**Comment by annekainicUSDS** [comment]
For fields that only had `schema` and not `uiSchema`, those fields didn't show up on the review page.

**Comment by annekainicUSDS** [comment]
Consider combining `schema` and `uiSchema`.

**Comment by annekainicUSDS** [comment]
Tools to link or check the validity of your form config would be really useful.

**Comment by fatimanoorva** [comment]
More examples and more visuals in the documentation would be helpful.

**Comment by fatimanoorva** [comment]
Would like to see more information about how US Forms could be integrated into existing applications/frameworks

**Comment by fatimanoorva** [comment]
Information about validators was hard to find in jsonSchema (not listed in contents; had to find it under "type-specific keywords")

**Comment by jcmeloni-usds** [comment]
@fatima-gov If everything in here is in its appropriate tickets and what not, let's close.  Thanks!
