### ISSUE TITLE
Design audit of the generated forms

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#193]
The styling of the forms right now is pretty bare bones and there is probably a lot we can do to improve it. It would be great if we had a designer do an audit of the forms right now and consider ways we could improve the styling, from superficial things to fonts and colors, to new UI patterns (e.g., more intelligent review pages).

**Comment by jcmeloni-usds** [comment]
@bernars-usa What are your thoughts on this, please? (I have thoughts but I want to hear yours!)

**Comment by bernars-usa** [comment]
I'm wondering what this audit might recommend that's different from the USWDS, given that's where our styling is inherited from.

**Comment by annekainicUSDS** [comment]
A lot is pulled from USWDS, but we also invented a lot of new things on the Vets.gov team that were not covered by USWDS (e.g., segmented progress bar, expandable question styles, review page). These new designs worked for us on Vets.gov, but we've never tested them with people beyond veterans. At some point it might be useful to revisit some of those decisions and make sure they apply to a larger audience.

**Comment by jcmeloni-usds** [comment]
Roger that.

**Comment by annekainicUSDS** [comment]
Once we're using USWDS 2.0, we'll revisit this.

**Comment by dmethvin-gov** [comment]
For the current version we plan to stay with the VA-inspired design additions to USWDS.
