### ISSUE TITLE
'ui:hidden' fields have their data wiped when hidden

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#198]
I had noticed this a while back but just got a chance to dig into it. Consider the following example:
<p>
<details><summary>Date field hidden by a checkbox</summary>

```js
          schema: {
            type: 'object',
            properties: {
              employed: { type: 'boolean' },
              'view:jobdate': {
                type: 'object',
                properties: {
                  jobStartDate: { type: 'string' }
                }
              }
            }
          },
          uiSchema: {
            employed: { 'ui:title': 'I am employed' },
            'view:jobdate': {
              jobStartDate: CurrentOrPastDateUI('Job start date'),
              'ui:options': {
                hideIf: (formData) => !formData.employed
              }
            }
          }
```

</details>
</p>

If the user clicks the check box, fills in the date, and then unchecks the box, `jobStartDate` is cleared and won't show up the next time the box is checked. This isn't too bad for a single data field, but could be a super frustrating experience if it's a lot of data (or even potentially a whole page of data if the user goes back and changes the answer on a previous page, then changes their mind again). 

The rationale for clearing the data in hidden fields is that [they can cause validation errors](https://github.com/usds/us-forms-system/blob/2410134ffda3767058ae7ef16e512e3fc5124632/src/js/state/helpers.js#L162-L166). However, it should be possible to keep data in "data the user entered" but not have it in "data that will be submitted to the server at some future point." We already take the data in `formData` and pass it through `transformForSubmit` so it's not perfectly correct while at rest when the form is being filled.

It seems like the issue is that we have two "sources of truth". One is the React/Redux store and the second, kept in parallel but in slightly different shape, is the `formData` object. uiSchema methods like `hideIf` reference the `formData` to make their decisions but affect React element rendering. This causes conflicts that the code [attempts to resolve](https://github.com/usds/us-forms-system/blob/ffd15c43556ab4108c1481b8d6163c8a1589a1ea/src/js/fields/ObjectField.jsx#L70-L75) by detecting redundant renders.

This affects any widget that might be written by us or others that needs to update React data. There could be subtle data integrity issues since React keeps props up to date *asynchronously* so I'm not sure when `formData` might be out of sync with them and what effects that might have.

**Comment by dmethvin-gov** [comment]
To that last point, the [React documentation for `shouldComponentUpdate`](https://reactjs.org/docs/react-component.html#shouldcomponentupdate) says:

> This method only exists as a performance optimization. **Do not rely on it to “prevent” a rendering, as this can lead to bugs.** Consider using the built-in PureComponent instead of writing shouldComponentUpdate() by hand. PureComponent performs a shallow comparison of props and state, and reduces the chance that you’ll skip a necessary update.

At this point I don't know enough about the React component lifecycle to tell if this warning applies to our code, but we're using `shouldComponentUpdate` in nearly all these components

**Comment by dmethvin-gov** [comment]
The [SchemaForm does something](https://github.com/usds/us-forms-system/blob/master/src/js/components/SchemaForm.jsx#L51-L61) that [this React team blog post](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#anti-pattern-erasing-state-when-props-change) specifically calls out as an antipattern, which makes me nervous. It's related to the multiple-sources-of-truth issue.

**Comment by jbalboni** [comment]
@dmethvin-gov That comment in the source code of ObjectField is no longer accurate, in the forked version of RJSF I removed the version of `formData` that was in local state. The only source of `formData` is the object in the Redux store. None of our uses of `shouldComponentUpdate` are intended to prevent errors, just to avoid having to do a pointless render (that's the intent, anyway, the actual effects might be different).

**Comment by dmethvin-gov** [comment]
For this particular situation, it looks like the conflict happens because there is `formData` in the Redux store but also derivative data in the React components themselves.

For the [DateWidget](https://github.com/usds/us-forms-system/blob/44bf861a0fe641f7d566c70cffb5d3ffd44ba9af/src/js/widgets/DateWidget.jsx) the `formData` is in "yyyy-mm-dd" format but there are three different HTML inputs that make up the date, one each for month, day, and year. Each of those three inputs has their value stored (along with some `touched` flags) in the component's local state. 

The DateWidget wipes the state [when it is initialized](https://github.com/usds/us-forms-system/blob/44bf861a0fe641f7d566c70cffb5d3ffd44ba9af/src/js/widgets/DateWidget.jsx#L24) and also [if the array page index changes](https://github.com/usds/us-forms-system/blob/44bf861a0fe641f7d566c70cffb5d3ffd44ba9af/src/js/widgets/DateWidget.jsx#L27-L31). For the first case, if the `formData` is the source of truth it should initialize local state (month/day/year and their touched states) from an incoming copy of the `formData` date. I don't think the second case should exist at all in the DateWidget, the bug it is trying to solve is most likely [a `key` prop hasn't been set on the parent component (or one of its ancestors)](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key).

**Comment by jbalboni** [comment]
Yeah, it looks like the date widget code could be simplified with a `key` prop somewhere. It hadn't occurred to me to use `key`s outside of lists of components.

For what it's worth, it's not clear to me what that has to do with data being cleared when fields are hidden (which is intentional and done in the reducer).

**Comment by dmethvin-gov** [comment]
We don't intend to change this design choice, so I'll close the ticket.
