### ISSUE TITLE
Create reference documentation site

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#200]
Here are some examples that we might follow when we get to the detailed per-widget documentation. Emphasis on pics of the rendered form elements and copy/paste of sample code.

https://joepuzzo.github.io/informed/?selectedKind=Inputs&selectedStory=Radio%20Input&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

**Comment by jcmeloni-usds** [comment]
@bernars-usa To your mind, anything to do here?

**Comment by dmethvin-gov** [comment]
I think any new work would make significant changes to the API so we wouldn't want to do this work for the current design.
