### ISSUE TITLE
Explore possibility of non-linear navigation

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#201]
Explore creating an option of using non-linear navigation. This has been a feature request by a few teams, and would make our library better able to handle much longer, more complex forms.

This would probably include some kind of side navigation with a list of all the pages that a user could click around through, and a way to make pages as complete or incomplete/invalid.

Another option would be to make our current navigation a wrapped around the formConfig, and to enable a user to create their own wrapper components that would include their own custom navigation.

The discovery work on this would probably include 2 streams of work:
1. Engineering discovery to understand what code changes would be needed in order for the library to accommodate this
2. Design work to come up with how this navigation would look and function

**Comment by jcmeloni-usds** [comment]
@annekainicUSDS @dmethvin-gov Given the clear lines we're drawing between library and instantiations of it (e.g. starter apps), this will likely be made easier to achieve in future phase(s) so we'll keep it for later.

**Comment by annekainicUSDS** [comment]
Duplicate of https://github.com/usds/us-forms-system/issues/169, closing this in favor of the other one.
