### ISSUE TITLE
Gather more research around the needs of potential adopters to inform future feature decisions

### ISSUE THREAD

**Issue by ju-liem** [usds/us-forms-system#203]
The USDS hackathon left us with lots of great observations around the experience of getting started with using the U.S. Forms System. We need to do some more research to understand how the USFS will be used to better inform our feature decisions moving forward.

I'm particularly interested in any existing gaps in the library that impact adoption.

Assigning to @bernars-usa to take point on planning and execution, involving other core team members as needed.

**Comment by fatimanoorva** [comment]
adding for reference re: feature gaps: https://github.com/usds/us-forms-system/issues/108

**Comment by bernars-usa** [comment]
In order to develop our next research plan, I'm going to clean up the user personas (outlined in #106). That work will happen this week.

**Comment by jcmeloni-usds** [comment]
Assigning to me for future.

**Comment by jcmeloni-usds** [comment]
This is basically the plan as os outlined here: https://github.com/usds/us-forms-system/wiki/Research-&-Testing-Strategy and you are all on it w/ the help of @kjurick
