### ISSUE TITLE
Identify exemplar forms

### ISSUE THREAD

**Issue by ju-liem** [usds/us-forms-system#204]
We need to show what is possible with the U.S. Forms System by providing a selection of exemplar forms.

To meet the goals we laid out in the original Project Charter, we should have at least three exemplars that cover the Easy, Medium, Hard spectrum.

**Comment by annekainicUSDS** [comment]
Another ticket created on this topic: https://github.com/usds/us-forms-system/issues/229?_pjax=%23js-repo-pjax-container. Consider referring to the most downloaded forms list from GSA for ideas of which forms to build examples for: https://www.gsa.gov/reference/forms.

Once we've identified the forms we'd like to build in this ticket, I think we should create individual tickets for each form and label them as things our open source community could pick up.

**Comment by jcmeloni-usds** [comment]
@ju-liem How is that list coming?

**Comment by annekainicUSDS** [comment]
I already built a couple of example forms for the last hackathon:
1. https://github.com/annekainicUSDS/usfs-g1145
2. https://github.com/annekainicUSDS/usfs-4506t

Can we just use these as a couple of examples? Maybe cleaning them up a bit, but they're basically ready to go.

**Comment by ju-liem** [comment]
In addition to the two forms @annekainicUSDS mentioned above, we've chosen the following three:

1. Application for Enrollment in Medicare Part B (https://www.cms.gov/Medicare/CMS-Forms/CMS-Forms/Downloads/CMS40B-E.pdf)
2. Application for a Social Security Card (https://www.ssa.gov/forms/ss-5.pdf)
3. U.S. Passport Renewal Application for Eligible Individuals (https://eforms.state.gov/Forms/ds82.pdf) - This one also has an online "form filler" that allows the user to fill out a digital form, then generates a PDF to print and mail in. (https://pptform.state.gov/?Submit2=Complete+Online+%26+Print)

**Comment by annekainicUSDS** [comment]
Could you please create separate tickets for each form?

**Comment by dmethvin-gov** [comment]
I've created a ticket for each form that we can work from. I'm leaving this ticket open for the moment to come up with some overall guidance for the 5 forms so they'll be somewhat consistent in how they look.

* How do we want to present the examples? The two that @annekainicUSDS did are clones of the starter app with only the [form.js](https://github.com/annekainicUSDS/usfs-g1145/blob/master/js/config/form.js) changed. (Well, and the `package.js` too but that's not important right now.) We could put full repos somewhere or just drop the `form.js` files in a repo with unique names perhaps?

* Thoughts about style and formatting? Should there be any comments sprinkled throughout the `form.js` file? If so, to what level of detail?

**Comment by annekainicUSDS** [comment]
Thanks @dmethvin-gov for creating those tickets! Good question about where we want these forms to eventually live. Maybe a single repo with all the exemplar forms?

In terms of style and formatting, comments might be helpful for particularly tricky parts, or parts where there might be more than one way of doing something and explaining why we picked a certain way (some of the conditional logic around showing content comes to mind).

**Comment by dmethvin-gov** [comment]
@ju-liem How far should we try to take these in showing them as sample forms? At the moment there are issues with practical use and I'm not sure how to address these points in the discussion that accompanies the examples.

* CMS40B-E: Requires individual signature and a witness signature.
* 4506-T: Requires individual signature.
* SS-5: Requires individual signature.
* DS-82: Requires attaching a photo, appearing at a govt office, having signature witnessed there, and paying application fee.

**Comment by dmethvin-gov** [comment]
I talked with @annekainicUSDS and we're going to put the `form.js` files in the docs folder, and create a codesandbox.io for each one. Since there is no back-end for any of these forms and they are really still paper forms, we'll assume we don't need to do anything on submit for now. I'll close this ticket since I think we've resolved the organizational issues.

**Comment by jcmeloni-usds** [comment]
Hold please - I want to make sure we're not closing anything without product oversight -- that would be me.
