### ISSUE TITLE
[Spike] Swappable architecture

### ISSUE THREAD

**Issue by ju-liem** [usds/us-forms-system#205]
The idea of a swappable architecture to allow people to use as much or as little of the library as they want/need -- while still offering an all-in-one package -- has been discussed a few times. Before we can decide if we want to take on this work, we need to do some experimentation to understand the size and impact of the undertaking.

**Comment by jcmeloni-usds** [comment]
@annekainicUSDS @dmethvin-gov Did you do the spike or is it in progress?  Are there notes somewhere about where you stand with it or what your thoughts were? Even just "we decided to punt for now and support RR4" is fine!

**Comment by annekainicUSDS** [comment]
We now have tickets to cover the individual elements within this spike, closing this ticket.
