### ISSUE TITLE
Estimation of effort and viability of additional data output formats

### ISSUE THREAD

**Issue by jcmeloni-usds** [usds/us-forms-system#21]
This is a low-priority research task to determine the estimation of effort for additional form submission output formats such as XML and CSV.

**Comment by jcmeloni-usds** [comment]
@fatima-gov I'd like to reflect this somehow as an implementation/example task for the starter app.  Thoughts on how to handle that in an issue/on the board?

**Comment by dmethvin-gov** [comment]
How about if we treat this as a just-in-time thing? I suspect most people who would want an alternate format will have other special needs so it would seem difficult to pin a cost on it in advance. Even the vets.gov folks didn't want plain JSON, they [required the keys to be modified](https://github.com/usds/us-forms-system/blob/f476ed0ff038403d04e531bbbae41f72290e23b5/src/js/actions.js#L125) by middleware.

If we just need a spitballed number, there are already libraries like [js2xmlparser](https://www.npmjs.com/package/js2xmlparser) that can do the transformation so I'd think a week is generous.

**Comment by dmethvin-gov** [comment]
This was a pretty vague ticket, and what it means depends on the needs of specific teams. If someone needs a different output format we can provide guidance on where you might be able to add it.
