### ISSUE TITLE
Versioning data and schema

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#210]
Often the schema for collected data might change over time, for example, to add, change, or remove fields. When that happens the front-end and back-end code need to agree on which "version" of they form data they are working with. That is especially true if it the user can save intermediate data (partially completed forms) to the server, or if the completed form is saved to individual fields in a SQL database for example.

The JSON Schema standard [defines a `$schema` property](https://schema.org/schemaVersion) and the vets.gov schemas define it, but that specifies the version of the schema itself--*not* the data being validated by the schema. 

Some folks have created a [SchemaVer](https://github.com/snowplow/iglu/wiki/SchemaVer) to address the issue. It's similar to SemVer used in software, but looks like `MODEL-REVISION-ADDITION`, i.e. dashes instead of dots. The [wiki spec](https://github.com/snowplow/iglu/wiki/SchemaVer) and [associated blog post](https://snowplowanalytics.com/blog/2014/05/13/introducing-schemaver-for-semantic-versioning-of-schemas/) have examples of schema changes and the version updates they require. Quoting the SchemaVer page linked above:

> * MODEL when you make a breaking schema change which will prevent interaction with any historical data
> * REVISION when you introduce a schema change which may prevent interaction with some historical data
> * ADDITION when you make a schema change that is compatible with all historical data

We should encourage use of a `SchemaVer` in the schema to help form creators understand this issue and ensure they don't save incompatible form data in their backend.

**Comment by jcmeloni-usds** [comment]
I like it!

**Comment by jcmeloni-usds** [comment]
@dmethvin-gov Going to make this a later-phase item to address via documentation or otherwise.

**Comment by dmethvin-gov** [comment]
This was a nice-to-have but not needed.
