### ISSUE TITLE
Eliminate vets.gov-isms in form submit and file upload

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#211]
There are still quite a few things that depend on server behavior specific to vets.gov like the use of ` req.setRequestHeader('X-Key-Inflection', 'camel')` [in actions.js](https://github.com/usds/us-forms-system/blob/2410134ffda3767058ae7ef16e512e3fc5124632/src/js/actions.js#L124) that expects the use of [particular Rails middleware](https://github.com/department-of-veterans-affairs/vets-website/issues/2953). Since servers and their configurations are so different this might be a good place to just have the app pass us a callback in `formConfig`. We pass it the `formData` and they use to submit the form, serializing it whatever way they want (JSON, XML, form-urlencoded). The same goes for file uploads.

**Comment by dmethvin-gov** [comment]
Adding the `va-growable-*` classes in [m-schemaform.scss](https://github.com/usds/us-forms-system/blob/master/src/scss/modules/_m-schemaform.scss). I suppose these might just need to be renamed to be generic but they may be defining some style we want to modify.

**Comment by jcmeloni-usds** [comment]
@dmethvin-gov Confirming this is still ongoing -- correct?

**Comment by dmethvin-gov** [comment]
Yes, I'll be making some changes once the new router lands.

**Comment by jcmeloni-usds** [comment]
Ok, moved to phase 2 and the 2.0.0-alpha1 milestone

**Comment by annekainicUSDS** [comment]
Another thing to add here: the "Submit again" button that only appears in dev and staging, we want to remove that now.

**Comment by dmethvin-gov** [comment]
Adding the rework of `stringifyFormReplacer` from #259, which currently has special case processing for various widgets.
