### ISSUE TITLE
Demonstrate different approaches to building a form config in sample forms

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#220]
As we build out sample forms to demonstrate how the library can be used, there are opportunities to include different techniques for building the form config.

One suggestion put forth in [this PR](https://github.com/usds/us-forms-system/pull/212) shows how you can create objects for the pages and fields in a form to minimize the risk of entering the wrong field name, since those need to be entered in multiple places. This may be more appropriate to include in a sample form as opposed to in our core documentation. Revisit this idea when we start building the sample forms.

**Comment by bernars-usa** [comment]
We might consider a new map within the documentation for sample forms of various types. As it stands, the [Quick Start](https://github.com/usds/us-forms-system/blob/master/docs/building-a-form/quick-start-example-formjs-file.md) and arguably the [Tutorial](https://github.com/usds/us-forms-system/blob/master/docs/getting-started/tutorial.md) could go there.

**Comment by ju-liem** [comment]
This is related to #204, but is not on the critical path for the end of September milestone date.

**Comment by dmethvin-gov** [comment]
With the forms in [docs/examples](https://github.com/usds/us-forms-system/tree/master/docs/examples) I think we have demonstrated a pretty decent variety of approaches. I'll close this but we can create new tickets if there are specific things we aren't showing that we need to.
