### ISSUE TITLE
Make definition outputs consistent

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#222]
Right now definitions output 2 things: `schema` and `uiSchema`. `schema` is usually an object, and `uiSchema` is sometimes an object, but more often is a function. This means that the way they are both imported in to the form config will be inconsistent, which could cause confusion.

Consider making both `schema` and `uiSchema` functions for consistency.

**Comment by dmethvin-gov** [comment]
Sounds like a good idea, as discussed in #219. 👍

**Comment by dmethvin-gov** [comment]
I guess the `schema` function arguments would be merged into the properties already being returned? So something like:
```js
function schema(options) {
  return { type: 'number', ...options };
}

// used like this?
number.schema();
number.schema({ min: 5 });
```
The `required` attribute is generally on the object *containing* the schema properties that go here, for better or worse, so it can't be set here.
