### ISSUE TITLE
Check unit tests for unfinished `expect()` assertions

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#227]
In doing some updates to the unit tests I couldn't figure out why some succeeded even when they should fail. Turned out they had just a bare `expect(thing)` rather than for example `expect(thing).to.be.true` so it wasn't testing a `thing`. The case I found was [in SubmitController](https://github.com/usds/us-forms-system/blob/4d1d6dc161d94fe5edfe465e601cabe9dc4d6146/test/js/review/SubmitController.unit.spec.jsx#L76) but it's a really easy mistake to make given the API and I found at least one other case in [SchemaForm](https://github.com/usds/us-forms-system/blob/4d1d6dc161d94fe5edfe465e601cabe9dc4d6146/test/js/components/SchemaForm.unit.spec.jsx#L108) where the same thing happens. We should review and fix all the cases and may need to push some issues back to vets.gov as a courtesy if they've forked functionality.

**Comment by jcmeloni-usds** [comment]
Approved. :)
