### ISSUE TITLE
Include examples directory with converted forms

### ISSUE THREAD

**Issue by anthonygarvan** [usds/us-forms-system#229]
This is a cool project!

Would be cool to start converting some popular standard forms: https://www.gsa.gov/reference/forms. 
 
Most SF forms aren't that long, but the exercise will give the team a clear sense of where the real gaps in functionality are.

This would be something easy for contributors to pick up as well, essentially just try to convert a real form and open issues for missing functionality.

If you can convert a bunch of SF forms it may also help build momentum: less ammo for people who say it's impractical or only does toy forms.

**Comment by annekainicUSDS** [comment]
Hi @anthonygarvan, thanks for contributing to our project! This is absolutely something we are planning to take on. We actually already have a ticket covering this work: https://github.com/usds/us-forms-system/issues/204. I'm going to link to your ticket in that one and close this ticket for now; but we will definitely refer to the link you provided for some of the most common forms.

Once we identify good forms to build, we'll create individual tickets for each, and perhaps you'll be interested in picking one of them up!
