### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#230]
It's been out for almost a year now, so we should upgrade to it! May need to consider the impact on users of the library (Vets.gov is still stuck on v15, though they want to upgrade too: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9143).

**Comment by annekainicUSDS** [comment]
Digging into the [React changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md#1600-september-26-2017), I don't think there are any breaking changes that would prevent us from upgrading to React 16. However, there are a couple of complications:

1. Our primary dependency, [rjsf](https://github.com/mozilla-services/react-jsonschema-form/blob/master/package.json#L85), is currently using React 15. We're [considering](https://github.com/usds/us-forms-system/issues/141) pulling what we need out of rjsf and into our library, which would give us greater control of the dependency management, but we haven't totally figured out that work yet.
2. React 17 is going to be [deprecating a bunch of the lifecycle functions](https://reactjs.org/blog/2018/03/29/react-v-16-3.html#component-lifecycle-changes). We can still use the lifecycle functions we currently use, but it will result in warnings, beginning in React 16. We may want to look into the work involved in upgrading those lifecycle functions along with the upgrade to React 16 before starting that work.

For these reasons, I think we're going to begin by [upgrading react-router 4](https://github.com/usds/us-forms-system/issues/168) and then revisit this work. @dmethvin-gov let me know if you agree!

**Comment by dmethvin-gov** [comment]
Fixed in 1.x-stable by #328
