### ISSUE TITLE
Inconsistent spacing between 1 line & 2 line checkboxes

### ISSUE THREAD

**Issue by rtluu** [usds/us-forms-system#233]
**Describe the bug**
Inconsistent spacing between 1 line & 2 line checkboxes

**To Reproduce**
This is due to a bug in the us-forms-system (missing >) in
.schemaform-first-field .schemaform-label, .schemaform-first-field > .usa-input-error in us-forms-system

**Steps to reproduce the behavior:**
1. Go to 'staging.vets.gov/education/gi-bill-school-feedback/'
2. Click on 'Submit Your Feedback'
3. Click on 'I want to submit my feedback anonymously' --> Continue
4. This is where the error occurred, but we put in an temporary fix until this is resolved in `us-forms-system`

**Screenshots**
![Screen Shot 2018-08-15 at 1.37.56 PM.png](https://images.zenhubusercontent.com/59975d8b8f62dc7798c35199/ac86b480-f26b-4d75-b2a7-2c6b95217528)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 68.0.3440.106

**Comment by annekainicUSDS** [comment]
PR was closed: #293
