### ISSUE TITLE
Create a visualization of U.S. Forms System technology for the contract

### ISSUE THREAD

**Issue by ButtersUSDS** [usds/us-forms-system#24]

**Comment by jcmeloni-usds** [comment]
I really like both of these! Definitely the non-pyramid works better for the contract, but both of these are super valuable and will be moving forward as well.

**Comment by ButtersUSDS** [comment]
I sent the non-pyramid illo to Traci via email. If she has language change requests, I will upload the revision here!

**Comment by jcmeloni-usds** [comment]
@ju-liem can this have a home too in the wiki do you think?

**Comment by ButtersUSDS** [comment]
@ju-liem here's the markdown for the two images (including alt text):

1. How U.S.Forms System Works
![Boxes Diagram of U.S. Forms technology](images/How-US-Forms-Work.png)

2. Hierarchy of Needs of a U.S. Form
![Pyramid diagram of U.S. Forms technology](images/Hierarchy-of-Needs.png)
