### ISSUE TITLE
Update the CheckboxWidget to support a description

### ISSUE THREAD

**Issue by rtluu** [usds/us-forms-system#243]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that checkboxes don't support descriptions that can provide supporting information for the checkbox item.

**Describe the solution you'd like**
Update the CheckboxWidget to support a description (a tooltip in this case), beneath the label

**Additional context**
We should be able to help implement this change cc: @annekainicUSDS

**Comment by dmethvin-gov** [comment]
I'm wondering if this could be done by passing a React tooltip component as [`options.title`](https://github.com/usds/us-forms-system/blob/0c30a6abccbf44ac49943eb0e19de5fa6135003c/src/js/widgets/CheckboxWidget.jsx#L26) perhaps?

**Comment by cehsu** [comment]
@1Copenut has recommended placing the description on a separate line due to the following accessibility considerations:
>The biggest thing I see with having the expand/collapse See an exampleinline is intrusion into the unencumbered hit space for the checkboxes. With labels properly associated to the inputs, users can click or tap on the label and have it select the box. Adding an inline element with its own hit space and own event listeners could disrupt that mental model.
...
>I favor the label on one line, the See an example trigger on another. It makes the page longer for sure, but allows us to keep clear hit spaces open, and provides a logical tracking order for keyboard users moving via TAB key.

**Comment by dmethvin-gov** [comment]
It looks like the original text had some examples? Can you post links to those? Because the original request mentioned a "tooltip" I thought it was asking for text that shows on hover. From the description and PR it sounds more like this is text that shows up below the checkbox+label and is independent of either.

**Comment by fatima-gov** [comment]
@rtluu Can you please share an example of the use case for this request? (we just want to understand the problem you are trying to solve for). Thanks so much!

**Comment by rtluu** [comment]
@fatima-gov For sure! We're looking to add examples to the GI Bill School Feedback Tool's potential feedback types. Here is a small mock up of what that would look like:

<img width="597" alt="screen shot 2018-08-21 at 4 41 05 pm" src="https://user-images.githubusercontent.com/1379629/44428480-77cb7280-a562-11e8-933c-a9d5343ec06b.png">

**Comment by dmethvin-gov** [comment]
I'm not sure PR #245 could implement what is mocked up there. Have you tried it?

For the moment should be able to get close with a [conditional field](https://github.com/usds/us-forms-system/blob/master/docs/building-a-form/available-form-features-and-usage-guidelines.md#conditional-form-fields). The only difference is that the user has to click the box to get the text to expand, but that is easily undone. It also ensures that if a user *does* check a box that they are shown the longer explanation of what they are claiming.

I'm curious, how are you consuming the form widgets? Are you using the starter app (or something simple) and a `form.js` file? Or are you using the widgets directly somehow? Is there a repo we can see?

**Comment by cehsu** [comment]
@fatima-gov @rtluu @dmethvin-gov Here is a mock of the desired UI (with the description field beneath the label, for the accessibility reason mentioned [above](https://github.com/usds/us-forms-system/issues/243#issuecomment-418502125)):
![gibill-feedback-examples.png](https://images.zenhubusercontent.com/5b0577164b5806bc2bd4524c/ecf57aa4-a103-4bd4-92ca-5e02f08b9e35)

@dmethvin-gov here is the accompanying [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/8308) on the [vets-website repo](https://github.com/department-of-veterans-affairs/vets-website).

**Comment by dmethvin-gov** [comment]
It doesn't seem like we need additional code to support something close to the mockup.

https://codesandbox.io/s/74608wzxz6

The second checkbox is just using the existing `ui:description` field with a React component. I switched the `form.js` to `form.jsx` for this demo but you would probably want to `import` the component instead in a real case.

```js
            "view:check2detail": {
              "ui:description": (
                <MoreInfoShow
                  linkText="See an example..."
                  className="schemaform-expandUnder-indent"
                >
                  Additional <i>important</i> stuff showing under check2 if the
                  link is clicked.
                </MoreInfoShow>
              )
            }
```

There's a separate discussion about whether this is a good design, but as far as the code goes I think it can do this already without more special-case props.

**Comment by fatima-gov** [comment]
@cehsu, @rtluu   – Adding to Dave's comment, we believe at the core of this is a content design issue that highlights some accessibility concerns.
 
Expanding and collapsing information at the answer level raises accessibility issues (e.g., screen reader problems, comprehension problems, discoverability, etc.). As such, it doesn’t feel like the right solution and we would rather recommend exploring ways to write the labels in a way more make more sense to the user. Alternatively, we think a better approach would be providing more information at the question level.
 
We have also generally looked into the use of tooltips which doesn’t seem to meet USWDS accessibility standards (there are several dated [issues](https://github.com/uswds/uswds/search?q=tooltip&type=Issues) in their repo discussing these concerns).
 
Additionally, I think we have ways to implement this a version of this option using the features that currently exist to edit checkboxes and add text above/below (please see Dave’s note above).
 
Ultimately, we want to be thoughtful about the features we add to this library to extent we can encourage better design standards and avoid potentially enabling bad user experience.
 
At this time, we won't be going forward with the  proposed solution on PR #245. However, if you like, we would like to continue this conversation with your team to further discuss your needs and any concerns you might have to get a better understanding.  Please feel free to let me know if that is something you would be interested in.
 
Again, thank you for raising this and helping contribute to this library!

**Comment by cehsu** [comment]
Thanks @fatima-gov @dmethvin-gov @annekainicUSDS. Looping in @1Copenut to provide any additional accessibility insights on the original design and also on the proposed alternative solution (creating a separate field to present the checkbox description). We (@erikphansen @rianfowler @rtluu ) will proceed with the alternative approach proposed.

**Comment by rianfowler** [comment]
We could link to a static content page that's opened in a separate tab and use anchors to jump to the appropriate section for each part. We wouldn't need to inline a bunch of progressive disclosures.

**Comment by rianfowler** [comment]
One other thought- what happens is the veteran selects the wrong checkbox? I'd say if there is no penalty or blocker there, then this isn't a required field and we could approach it differently with some stakeholder input.

**Comment by fatima-gov** [comment]
Thanks, all! Looks like there is no additional work here as it relates to this library, so I will go ahead and close out this issue for now. Please do let us know if we can assist further.
