### ISSUE TITLE
Make code samples and screenshots reflect same content

### ISSUE THREAD

**Issue by ju-liem** [usds/us-forms-system#255]
We have several instances where the screenshots and the code samples in our documentation do not reflect the same content. For ease of understanding, these should be reconciled.

Example:
https://github.com/usds/us-forms-system/blob/master/docs/building-a-form/available-form-features-and-usage-guidelines.md#radio-button-group

The screenshot in the above example is about VA compensation, while the code sample is about favorite animals. 

Whimsical is fine. Practical is fine. But consistency is key.

**Comment by jcmeloni-usds** [comment]
Julie will sweep through the documentation.

**Comment by jcmeloni-usds** [comment]
I didn't get to this but I am assigning my NON-USDS self to this and will do this next week because yay open source.

**Comment by jcmeloni-usds** [comment]
tagging my private self: @jcmeloni

**Comment by dmethvin-gov** [comment]
The docs are still fine with the images not matching the code sample. If someone would like to fix them a pull request would be welcome though,
