### ISSUE TITLE
On the review page, pagePerItem pages with `depends` functions are not correctly passed `index`

### ISSUE THREAD

**Issue by jbalboni** [usds/us-forms-system#266]
**Describe the bug**
Normally, the `depends` property in a page config is passed `index` as a second parameter for `pagePerItem` pages. But in `ReviewChapters`, we run the `depends` logic before those `index` properties are set, because we call `getActivePages` before `expandArrayPages`. In `routing.js` we do the opposite, so the logic works correctly outside of the review page.

The result is that pages that have a `depends` function that needs `index` will be shown/hidden incorrectly on the review page.

**To Reproduce**
Use a page config with the following options:

```
{
  path: 'some-url/:index`,
  showPagePerItem: true,
  arrayPath: 'someArray',
  depends: (formData, index) => typeof index !== 'undefined'
}
```
Pages will be visible on normal form pages, but not on the review page.

**Expected behavior**
`index` is populated when calling `depends`

**Comment by jcmeloni-usds** [comment]
@jbalboni Confirming that PR #267 addressed this and we can close this? (thanks, if so!)

**Comment by jbalboni** [comment]
@jcmeloni-usds Yep, this can be closed.

**Comment by jcmeloni-usds** [comment]
Yay! Thanks.
