### ISSUE TITLE
Document release process (differences between 1.x-stable and 2.x-experimental)

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#270]
We need to come up with a better solution for releasing patches for bug fixes quickly, and group breaking changes in chunks and release those more slowly. Our current release process does not enable us to do this.

**Comment by annekainicUSDS** [comment]
Notes from conversation with Vets.gov team:

- The main breaking changes (definitions and analytics) are not a big lift for them to upgrade to (they want to be making changes to the analytics now anyway)
- Not sure yet about the routing changes what the lift will be until they see the changes
- General goals: they want breaking changes to come slowly (~4-6 weeks) and in large chunks so they can plan around them, while bug fixes to be made immediately
- They want to stay up to date as much as possible
- We can agree on some set expectations (e.g., not merging patches on a release that is 2-3 major releases ago)
- One potential solution is pushing breaking changes to a separate branch before they get released so that patches can still be made to master and released more quickly (this will be easier to implement going forward, but may be trickier to go backwards and do because breaking changes have already been merged to master, but we could create a branch from a patch and move those commits over to that branch and release those as a patch)

**Comment by jcmeloni-usds** [comment]
Assigned to myself to review and comment.  Putting in Phase II.

**Comment by annekainicUSDS** [comment]
One thing we may need to revisit when looking at the release process is our CircleCI config, which deploys only the "production" branch. If we change our branching strategy, this config may need to change.

**Comment by jcmeloni-usds** [comment]
Dave has been keeping wiki page up to date so we'll cal this good.

**Comment by jcmeloni-usds** [comment]
Closing this because of the previous comment, and also because there isn't an experimental branch yet.  but pleae promise when you get there, you'll document the differences. :)
