### ISSUE TITLE
Invalid ArrayField items to open in edit mode

### ISSUE THREAD

**Issue by cvalarida** [usds/us-forms-system#273]
**Is your feature request related to a problem? Please describe.**
We can have invalid information in an ArrayField item with no way of showing validation errors.

Context:
- We've got an array of objects with required fields
- `reviewMode` is set to `true` in `ui:options`

Steps to reproduce:
1) Start the form
    - No array exists in the form data for this field yet
2) Navigate to the page
    - An array with a single empty object is now in the form data
3) Navigate _back_ to the previous page
4) Go forward to the page with the array field

Result:
Something like this
![image](https://user-images.githubusercontent.com/12970166/45770423-34166800-bbf7-11e8-9683-6b89f1231f14.png)

This is because the `ArrayField` constructor initializes the `editing` state for all items as `false` if the array exists in the form data and the last item in `reviewMode` arrays won't start in edit mode by default like non-`reviewMode` arrays.

**Describe the solution you'd like**
In the constructor, initialize the `editing` state to `true` if there are validation errors for that item.

**Describe alternatives you've considered**
We could, alternatively, display error messages on an entire array item if any exist within the item, but that's...pretty complicated.

**Additional context**
Without this feature, we can get stuck on a page without a clear sense of why we're not allowed to move forward (no validation messages appear).

**Comment by annekainicUSDS** [comment]
@cvalarida I've looked into this bug and see what you mean. In your proposed solution, do you imagine all array items to be in editing state if there are validation errors in them, or only the last item to be in editing state if there are validation errors in that one? I was able to create a situation where there are multiple array items and both have validation errors, but when going back and then forward again both are collapsed.

<img width="439" alt="screen shot 2018-09-24 at 4 00 37 pm" src="https://user-images.githubusercontent.com/25183456/45975767-01afa500-c013-11e8-809c-796420e80d14.png">

**Comment by cvalarida** [comment]
I think it makes the most sense to open any item in the array in edit mode if there are validation errors in it. That way, when we try to advance to the next page, we aren't stuck on the current one with no explanation. If an item is in edit mode, we'll see those validation messages.

**Comment by dmethvin-gov** [comment]
Should we generalize that to say that any page with a validation error opens in edit mode?

**Comment by annekainicUSDS** [comment]
Yes makes sense! Although I believe only array pages and review pages will be affected by this, as regular form pages are always in "edit" mode (they never collapse).

**Comment by cvalarida** [comment]
Yeah, I think that makes a lot of sense!

This is maybe beyond the scope of this issue, but for the review page, rather than expanding each chapter that contains validation errors, it might make sense to stick with the alert pattern that's already been established. When a user tries to submit from the review page, but a chapter has validation errors, I think what we do now is highlight it and throw up a little alert sign. If we could do that before the user hits submit, I think that'd be ideal.

**Comment by dmethvin-gov** [comment]
Fixed in #321
