### ISSUE TITLE
Edit buttons would benefit from aria-label attribute to help screen readers

### ISSUE THREAD

**Issue by 1Copenut** [usds/us-forms-system#275]
**Describe the bug**
There is an outlined Edit button on several forms that allows users to make changes without having to go back several steps. This is very beneficial to sighted users because they can draw a relationship between the heading and the edit label. Assistive device users only hear the word "Edit" read out, and are asked to determine "Edit which data?" on their own.

**To Reproduce**
1. Go to any form using the Edit form inline pattern, as shown in screenshot below
2. Enter data for all views, until you get to the review and edit inline step
3. Turn on a screen reader of your choosing (JAWS, NVDA, VoiceOver)
4. Click to expand an accordion menu
5. Press `TAB` until you hear "Edit, button, collapsed` or some similar announcement

**Expected behavior**

Assistive device users should hear a more descriptive label, such as "Edit application information". Because this is a forms library, the emphasis is on adding a prop that could be passed into the `<button>` so teams can configure the `aria-label` attributes to best represent their content.

**Possible code change**
On line 124 of `src/js/review/ObjectField.jsx` https://github.com/usds/us-forms-system/blob/95c6518d5a0cc3a40f7376840760026b16007e13/src/js/review/ObjectField.jsx#L124 we could add an `aria-label` attribute that could be passed as a prop:

```javascript
<button
  aria-label={this.props.ariaLabel:String}
  type="button"
  className="edit-btn primary-outline"
  onClick={() => formContext.onEdit()}>
  Edit
</button>
```

**Screenshots**
![screen shot 2018-09-19 at 4 42 17 pm](https://user-images.githubusercontent.com/934879/45784148-5b882780-bc2d-11e8-9865-df53a9725c3a.png)

**Desktop (please complete the following information):**
 - OS: [Win10, MacOS]
 - Browser [IE11, Chrome, Firefox, Safari]
 - Version [latest]

**Additional context**
I'm looking for a way to pass in a string prop that appears as an `aria-label` on the final rendered HTML. This allows the longer descriptions to appear in button lists for JAWS, NVDA, and VoiceOver. Screenshots for JAWS and NVDA below.

---

**JAWS - IE11**
![screenshot 3](https://user-images.githubusercontent.com/934879/45784207-8f634d00-bc2d-11e8-9892-cac5e423c5cd.png)

---

**NVDA - Firefox**
![screenshot 5](https://user-images.githubusercontent.com/934879/45784277-bfaaeb80-bc2d-11e8-8a76-2545f6f4565f.png)

**Comment by dmethvin-gov** [comment]
@1Copenut It looks like [we have the title text available](https://github.com/usds/us-forms-system/blob/95c6518d5a0cc3a40f7376840760026b16007e13/src/js/review/ObjectField.jsx#L123-L124), would it be okay in that case to use "Edit" plus title text for aria-label? So for the example above it would be `aria-label="Edit Applicant Information"`.

**Comment by dmethvin-gov** [comment]
Instead of a boolean, it might just be easier to let the form creator set the `aria-label` on that button through some option in the form config but have the default be "Edit" plus the page title.

**Comment by 1Copenut** [comment]
That does sound easier having `Edit ${title}` as a default and config file overrides.

**Comment by 1Copenut** [comment]
@dmethvin-gov Do you feel this issue is ready to be closed?

**Comment by dmethvin-gov** [comment]
Yep, thanks!
