### ISSUE TITLE
Description text is displayed twice

### ISSUE THREAD

**Issue by jbalboni** [usds/us-forms-system#276]
**Describe the bug**
If you use the `showFieldLabel` option on an object field and also use `ui:description`, then that description will be displayed twice.

**To Reproduce**
Here's an example schema and uiSchema:

schema:
```
'patientAcknowledgment': {
  type: 'object',
    properties: {
      'acknowledgment': {
        type: 'boolean'
       }
    }
},
```

uiSchema:
```
'patientAcknowledgment': {
  'ui:title': 'Patient Acknowledgment',
  'ui:description': 'This is displayed twice',
  'ui:options': {
    showFieldLabel: true
   },
   'acknowledgment': {
      'ui:title': 'Patient Acknowledgment'
    }
},
```

**Expected behavior**
The description should display once

**Additional context**
This is happening because both `FieldTemplate` and `ObjectField` can display description text. Normally, `FieldTemplate` defers to `ObjectField`, but `showFieldLabel` forces `FieldTemplate` to display labels and description fields (sort of misleadingly) for object fields.

**Comment by dmethvin-gov** [comment]
Is this a dup of #260?

**Comment by jbalboni** [comment]
Gah, I don't know how I missed that one. Closing.
