### ISSUE TITLE
Improvements From VA 508 Review - Q4 2018

### ISSUE THREAD

**Issue by 1Copenut** [usds/us-forms-system#277]
The VA 508 office has reviewed an application using the US Forms System and identified a few improvement opportunities. This issue is being opened as a way to collect the individual issues in a single place for tracking.

## Audit Information
* Dates:
  * September 17, 2018
  * November 27, 2018
* OS: Windows 7 64 bit Enterprise, Service Pack 1
* Browser: Internet Explorer 11
* Screen Reader: JAWS 2018

## Related Issues
* [#265 - [SCREENREADER]: Month,  Day, Year combo box pattern not announcing legend to assistive devices](https://github.com/usds/us-forms-system/issues/265)
* [#275 - Edit buttons would benefit from aria-label attribute](https://github.com/usds/us-forms-system/issues/275)
* [#278 - Inline error messages are announcing to screen readers on correction, not subsequent errors](https://github.com/usds/us-forms-system/issues/278)
* [#279 - Text and inputs added dynamically should be announced by screen readers](https://github.com/usds/us-forms-system/issues/279)
* [#316 - Inputs with autocomplete="false" are reporting incorrect formatting in latest axe-core ruleset](https://github.com/usds/us-forms-system/issues/316)
* [#320 - [KEYBOARD]: Can focus management be improved for Edit or Add panels that are added before their trigger button](https://github.com/usds/us-forms-system/issues/320)

**Comment by dmethvin-gov** [comment]
Since we have individual tickets open for the remaining unresolved 508 issues, I'll close this and we can continue discussion on those tickets.
