### ISSUE TITLE
Clean up test suite libraries

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#286]
We use a variety of different libraries right now for our unit tests, some of which serve the same purpose:

1. chai
2. chai-as-promised
3. choma
4. enzyme
5. enzyme-adapter-react-15
6. jsdom
7. mocha
8. react-dom
9. react-test-renderer
10. sinon
11. skin-deep

Decide on which we can eliminate/consoldiate. This will require some work to also change our unit tests if we want to use one library over another. I would consider this lower priority.

**Comment by dmethvin-gov** [comment]
This is super low priority so I'll assume that if the project has major new development that this would be fixed as part of the normal flow of new code and rewrites.
