### ISSUE TITLE
Clarify the license: CC0 or ISC?

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#296]
The [package.json says we're ISC](https://github.com/usds/us-forms-system/blob/28b9c581a6d48ca8656bc5481c34f17ffc439585/package.json#L25) but the [LICENSE.md says we're CC0](https://github.com/usds/us-forms-system/blob/28b9c581a6d48ca8656bc5481c34f17ffc439585/LICENSE.md).

**Comment by jcmeloni-usds** [comment]
Should be CC0.

**Comment by dmethvin-gov** [comment]
OK, looks like the identifier in the `package.json` file should be [`"CC0-1.0"`](https://spdx.org/licenses/) then.
