### ISSUE TITLE
widgetClassNames array doesn't split the class names appropriately

### ISSUE THREAD

**Issue by cvalarida** [usds/us-forms-system#314]
**Describe the bug**

When passing an array to `widgetClassNames` in `ui:options` for a string field, the class name passed along to the input is all the array elements joined with a comma delimiter.

**To Reproduce**

1. Define a string field and pass it the following:
   ```
      'ui:options': {
        widgetClassNames: ['usa-form-group-year', 'reset-float'],
      },
   ```
2. Load up the form and examine the text input
3. The element has `class="usa-form-group-year,reset-float"`

**Expected behavior**

I expected `widgetClassNames` to split up the array and pass individual class names separated by a space.

**Screenshots**
Not really much by way of screenshots here.
![image](https://user-images.githubusercontent.com/12970166/47944331-03914180-deb8-11e8-983c-39135e2a5391.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 69.0.3497.100

**Additional context**

I can specify a string for `widgetClassNames` of `'usa-form-group-year reset-float'` and it works as expected. I think this happens because [`Array.prototype.toString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toString) is being called implicitly when an array is passed. Since the option name is plural, I just assumed it accepted an array (though to be fair, I've only seen it as a string).

I'd say this definitely isn't a high priority since there's an easy way around it for now (and so much more for y'all to be doing!), but I think there are a couple ways it could be handled:
1. The library informs me, the developer, that the option only accepts a string
2. The option accepts an array or string
   - If it's an array, it calls `widgetClassNames.join(' ')`

**Comment by dmethvin-gov** [comment]
There's already documentation mentioning that this needs to be a string of space-separated class names, see [the comments in this sample file](https://github.com/usds/us-forms-system/blob/57099b4f533d501046a060099a9b8ff02d935524/docs/building-a-form/about-the-schema-and-uischema-objects.md#configuring-uischema-using-us-forms-system-options). Like most of the `formConfig` except the actual `schema` part, there aren't a lot of checks to be sure the data is correct. We could add some checks to be sure it's a string but I think there is a solution that is even better.

We use the [classnames](https://github.com/JedWatson/classnames#readme) package in several places to merge and process class names, and it allows just about anything. So in places like [CheckboxWidget](https://github.com/usds/us-forms-system/blob/95c6518d5a0cc3a40f7376840760026b16007e13/src/js/widgets/CheckboxWidget.jsx#L15) you should already be able to pass either an array or an object with `true`/`false` values for . It's just that we don't use it consistently, so for [TextWidget](https://github.com/usds/us-forms-system/blob/95c6518d5a0cc3a40f7376840760026b16007e13/src/js/widgets/TextWidget.jsx#L17) and several others it's just put in directly so it has to be a string. If we wrap all those direct uses in a call to `classname()` I think we'll get this feature for free.

Would you like to put together a PR for this? I think it should be pretty easy to do, the hardest part will be to add a few tests to confirm it's working.

**Comment by cvalarida** [comment]
Ooh, I forgot about the classnames library. Good call!

I'll whip up a PR that:
- [ ] Passes the `widgetClassNames` prop in `TextWidget` through the `classnames` library
- [ ] Tests that it's working properly (and doesn't break existing usages)
- [ ] Updates the documentation to match the new usage

If there's anything else it should do, please let me know!
