### ISSUE TITLE
Inconsistent behavior with "expandUnder" within arrays

### ISSUE THREAD

**Issue by briaguya** [usds/us-forms-system#322]
**Describe the bug**
When using expandUnder and an expandUnderCondition on a field within an array object as I have set up in [this branch of the starter app](https://github.com/briaguya/us-forms-system-starter-app/tree/expand-under-bug), the conditional field appears as visible until a value is entered in any field within the array. This only happens when adding the first item, the behavior is correct on any subsequent array items. See screenshots for more detail.

**To Reproduce**
I have a repo set up where the issue is visible: https://github.com/briaguya/us-forms-system-starter-app/tree/expand-under-bug

1. Grab the code from the linked repo
2. Run it
3. Click around

**Expected behavior**
The expandUnder item doesn't expand unless the condition is met.

**Screenshots**
##### By default it shows as expanded for the first item:
![issue](https://user-images.githubusercontent.com/6384156/49857095-3ed83780-fdb7-11e8-96d9-af3c3eae98bd.gif)

##### After selecting a value it behaves correctly:
![correct](https://user-images.githubusercontent.com/6384156/49857168-7646e400-fdb7-11e8-8a95-84d319b5b208.gif)

##### It even jumps into correct behavior after entering data in an unrelated field:
![unrelated](https://user-images.githubusercontent.com/6384156/49857227-a3939200-fdb7-11e8-8b11-ffbee3b514f4.gif)

##### And it seems to work perfectly with any subsequent array items:
![workswithmultiple](https://user-images.githubusercontent.com/6384156/49857299-d5a4f400-fdb7-11e8-98e6-d06013a8b418.gif)

**Desktop:**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 70

**Comment by annekainicUSDS** [comment]
Hi @briaguya, thanks for filing this issue! We're looking into it and will report back once we identify what is causing that bug you noticed. Thanks!

**Comment by annekainicUSDS** [comment]
@briaguya If you add `"ui:collapsed": true` to schema for `otherThing` (as shown below), the field will be hidden on initial page load. The `"ui:collapsed"` property is what gets toggled each time the schema is updated and the answer to a question that another field expands under is changed. In order to set the field to be hidden on initial page load, that property needs to be set to `true`. It's a little confusing, and the docs aren't clear about this, so I will update the docs as well.

```
otherThing: { type: "string", "ui:collapsed": true },
```

Let me know if this works for you!

**Comment by briaguya** [comment]
@annekainicUSDS thank you so much! This appears to fix the issue!

I tried adding `"ui:collapsed": true` to the `uiSchema`
```
otherThing: {
  "ui:options": {
    expandUnder: "thing",
    expandUnderCondition: "other"
  },
  "ui:collapsed": true
}
```
to no avail, but hadn't thought to try putting it in the standard `schema`

Thanks again for the help and prompt response!

**Comment by annekainicUSDS** [comment]
So glad that worked for you! Let us know if there's anything else we can do to help in the future!
