### ISSUE TITLE
Looking for a way to customize beforeText, afterText props

### ISSUE THREAD

**Issue by easherma** [usds/us-forms-system#335]
**Is your feature request related to a problem? Please describe.**
before and afterText props have some props that cannot be easily removed or customized at the moment. For instance, at the moment they have arrow icons being used for progress/form navigation. However, I don't see this anywhere in the USWDS spec, and either way I ought to be able to customize this. 

**Describe the solution you'd like**
Use the form system configuration to be able to set button props to something custom (or nothing).

**Additional context**
https://github.com/usds/us-forms-system/blob/ffd15c43556ab4108c1481b8d6163c8a1589a1ea/src/js/components/ProgressButton.jsx#L15

Thanks!

**Comment by dmethvin-gov** [comment]
It would be nice to avoid having to define and pass through a bunch of optional positional layout control options that grow without end. I don't yet know how that will look at the top level though. As far as React components are concerned, this talk by Kent Dodds is an inspiration to find a better way: https://www.youtube.com/watch?v=eLNS6GMejjw

**Comment by dmethvin-gov** [comment]
I think that is probably the best way to go. Although the names imply they're "text" they really do seem to be used for icons. In that case I wonder if it would be better to add those icons via CSS `::before` or `::after`. I don't see that `afterText` is used anywhere at all right now.

**Comment by easherma** [comment]
They are used in the back and continue buttons.

**Comment by dmethvin-gov** [comment]
I think the best way to do this would be expose the [button label](https://github.com/usds/us-forms-system/blob/d9f99a33c2a1d64d7f1aa5f76ac970dc07f65cc4/src/js/containers/FormPage.jsx#L124) as part of i18n efforts and then the user can specify special characters as part of that.
