### ISSUE TITLE
Demo on gh-pages

### ISSUE THREAD

**Issue by epicfaace** [usds/us-forms-system#336]
It would be nice to have a demo on gh-pages with the following:

- Previews of the demos here: https://github.com/usds/us-forms-system/tree/master/docs/examples
- a `formConfig` editor which lets you specify your own JSON and preview the form corresponding to that config

Perhaps it could be modeled off the [rjsf playground](https://mozilla-services.github.io/react-jsonschema-form/).

**Comment by dmethvin-gov** [comment]
I had started setting up the demos on CodeSandbox but that site was acting a bit flakey a month ago. When it works it's nice though because you get a playground essentially for free: https://codesandbox.io/s/n0j1zvkx70

**Comment by dmethvin-gov** [comment]
The codesandbox is not perfect but does provide a way to try things out without installing it locally so I'll close this.
