### ISSUE TITLE
Test integration of library with basic static page

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#34]
See if things work without React, how long it takes to compile/render, etc.

**Comment by jcmeloni-usds** [comment]
Def low priority but I am super interested in this and think it could be helpful for different types of adoption.

**Comment by jcmeloni-usds** [comment]
Confirming still a low priority....but I wouldn't be surprised if it's something we were asked about sooner rather than later so perhaps just having someting on the wiki would help.

**Comment by jcmeloni-usds** [comment]
I'm closing thi; from a product perspective it makes the most sense to continue to roll examples out as starter apps.
