### ISSUE TITLE
Add retrospective and learnings documents

### ISSUE THREAD

**Issue by dmethvin-gov** [usds/us-forms-system#349]
Let's be sure we put our information in the repo here and reference it in the readme.

**Comment by easherma** [comment]
@dmethvin-gov would love to see these docs! we're still rolling with this repo for now at City of Austin, and debating further refactoring vs migrating to a different project.

**Comment by dmethvin-gov** [comment]
Here's a first draft, I decided to post it in the wiki so we can edit it when needed. I've also attached a presentation in PowerPoint format that covers most of the same points.
[USFS_Retrospective_Final.pptx](https://github.com/usds/us-forms-system/files/3024348/USFS_Retrospective_Final.pptx)


https://github.com/usds/us-forms-system/wiki/Lessons-from-the-Post-Phase-1-Discovery-Sprint

**Comment by easherma** [comment]
Awesome, thanks so much!
