### ISSUE TITLE
Define & Document User Personas

### ISSUE THREAD

**Issue by ButtersUSDS** [usds/us-forms-system#35]
- [x] Include philosophy and rationale behind the decisions.

- [x] Include scenarios for each user persona

**Comment by ButtersUSDS** [comment]
The draft of this issue is [here](https://github.com/usds/us-forms-system/wiki/User-Personas-&-Scenarios-(Phase-1)).

Couple points:
• would love a review by an engineer since I have 3 developer personas
• I made a point in the overview that _end users_ are intentionally not one of this project's user personas. I'd love that to be validated by the team!

**Comment by jcmeloni-usds** [comment]
Assigning to myself to review.

**Comment by jcmeloni-usds** [comment]
Closing as finished first iteration; opening new ticket for updates.
