### ISSUE TITLE
Develop analytics strategy

### ISSUE THREAD

**Issue by ju-liem** [usds/us-forms-system#36]
- [ ] Determine success metrics
- [ ] Document the analytics approach on the wiki

**Comment by jcmeloni-usds** [comment]
@ju-liem Is this for analytics re: project success, or analytics as regards how to implement analytics into forms using the forms system (e.g. attaching GA triggers to form elements, etc)?

**Comment by ju-liem** [comment]
@jcmeloni-usds This is around project success.

**Comment by jcmeloni-usds** [comment]
Cool cool - thank you!

**Comment by jcmeloni-usds** [comment]
@ju-liem How's this going?

**Comment by jcmeloni-usds** [comment]
Closing this; phase 1 project success metrics are wholly around the original goals which have binary answers...
