### ISSUE TITLE
Make an inventory of all features currently offered by the Forms library

### ISSUE THREAD

**Issue by ButtersUSDS** [usds/us-forms-system#37]
- [x] List everything from forms on Vets.gov
- [x] Add anything that is not there but IS included in react-json-schema-form (RJSF).

**Comment by kaschm-usds** [comment]
Per conversation with @ButtersUSDS, I'm going to jump in to: 

- Create table at top of [inventory features page](https://github.com/usds/us-forms-system/wiki/Inventory-of-Existing-Features) for quick scan of what exists, anchor link down to the more comprehensive feature explanations 
- Create table on new page of wiki for the 'gaps' we are aware of. We'll hold off on longer explanation of these features for now (not prioritized considering how much else there is to do)

The thinking here is that a PM or Designer from another team may want to quickly scan the list to see what's there and what's not. Current format is lovely (with pictures!) but hard to scan.

**Comment by jcmeloni-usds** [comment]
Assigning to @annekainicUSDS to review and ok at her leisure.

**Comment by jcmeloni-usds** [comment]
Closing this as complete -- the information will be living, however.  Opening another ticket for "gap" page suggestions.
