### ISSUE TITLE
Make an inventory of features in existing USDS web forms that are NOT offered by the Forms library

### ISSUE THREAD

**Issue by ButtersUSDS** [usds/us-forms-system#38]
- [x] Interview Laura Kadamus and Andy Lewandowski (DHS)
- [ ] Interview Jared from SBA
- [ ] Interview UX lead from HHS
- [ ] Interview Carola (Dept. of Ed)

**Comment by jcmeloni-usds** [comment]
Hi! What's the progress on this?

**Comment by ButtersUSDS** [comment]
@jcmeloni-usds, @kaschm-usds and I created a page in the wiki [here](https://github.com/usds/us-forms-system/wiki/Inventory-of-Feature-Gaps). I have not done all the UX interviews per ticket criteria, but can keep plugging away on those. I need to write a separate ticket for the PRA guide and prioritize that!

**Comment by jcmeloni-usds** [comment]
We'll stop here and call this ok for now; opening a new ticket for iterations.
