### ISSUE TITLE
Write a Research & Testing Strategy page

### ISSUE THREAD

**Issue by ButtersUSDS** [usds/us-forms-system#39]
https://github.com/usds/us-forms-system/wiki/Research-&-Testing-Strategy

This would explain the different streams of our research and the deliverables each stream will lead into. It would also clarify which research informs our Phase 1 work and which will inform later Phases.

**Research Streams include:**
1. What’s necessary to make a super usable open source library **for Developers**?
- [x] Research practices
- [x] List of predicted documents and other deliverables
- [x] Usability Testing Plan
- [ ] Target Dates
2. What’s necessary for **Non-technical Users** to easily use this library?
- [x] Research practices
- [x] List of predicted documents and other deliverables
- [x] Usability Testing Plan
- [ ] Target Dates
3. What are the most important **features** to add to the library next?
- [x] Research practices
- [x] List of predicted documents and other deliverables
- [x] Usability Testing Plan
- [ ] Target Dates

**Comment by jcmeloni-usds** [comment]
Please do not involve too much of Liz's time -- maybe an hour or two here or there if she has the time to spare. Marcy has explicitly and rightfully asked that we do not take Liz's focus away from her DSVA work.  Thanks!

(cc @amiklik for awareness)

**Comment by ButtersUSDS** [comment]
Copy that!

**Comment by ButtersUSDS** [comment]
I am finished with my draft Research & Testing strategy page, except for dates. @ju-liem can we find some time to work on those?

https://github.com/usds/us-forms-system/wiki/Research-%26-Testing-Strategy/_edit

**Comment by jcmeloni-usds** [comment]
Assigning to myself and @ju-liem to review; let's get time together to do it or do it in parallel and leave comments -- your call, jmac

**Comment by jcmeloni-usds** [comment]
Closing in lieu of #109
