### ISSUE TITLE
Create visualization of how US Forms integrates with other systems

### ISSUE THREAD

**Issue by ButtersUSDS** [usds/us-forms-system#44]
- [ ] Show Authentication

- [ ] Show Back End

- [ ] Show shim layer

- [ ] Make it clear that US Forms is NOT any of those things

**Comment by jcmeloni-usds** [comment]
Hi! What's the progress on this?

**Comment by ButtersUSDS** [comment]
@jcmeloni-usds I was prioritizing the PRA stuff per @amiklik, but this was next on the list. I would want to consult with an engineer to make sure I'm communicating accurate information. Any recommendations on who to tap?

**Comment by jcmeloni-usds** [comment]
@ju-liem Can you please confirm that we don't need a visualization here, and that for the first iteration of documentation what we really need is just a couple prose-based examples of integration paths and how it's up to the developer?  Thanks!

**Comment by bernars-usa** [comment]
Does https://github.com/usds/us-forms-system/blob/master/docs/getting-started/installing-the-us-forms-system-in-an-existing-application.md satisfy this issue? I'm not entirely clear what's being asked for here.

**Comment by ButtersUSDS** [comment]
@bernars-usa I originally conceived of this as an illustration/diagram to quickly show the parameters of the tool, specifically that it does not include authentication or back end integration. But I don't believe this was a must have at all. Feel free to close!

**Comment by ju-liem** [comment]
Per some discussion @bernars-usa and I will work on prose examples to include in an existing Help topic. I'm closing this issue, though we may revisit it at some point in the future.

**Comment by bernars-usa** [comment]
For Future Us, this is the topic I'd like to elaborate on: https://github.com/usds/us-forms-system/blob/master/docs/getting-started/installing-the-us-forms-system-in-an-existing-application.md
