### ISSUE TITLE
Initial Launch List - Interested Parties

### ISSUE THREAD

**Issue by kaschm-usds** [usds/us-forms-system#49]
Build a list of tech folks who are interested in learning more about using US Forms System to build forms for government. Consider local, state, and fed tech teams or offices.

**Comment by kaschm-usds** [comment]
FYI, created a form to help collect names / etc: https://goo.gl/forms/F40cgqwWgbEPoplW2

We should probably formalize this at some point (into an list we can manage from an email list manager system, whatever it is), but let's just start here.

**Comment by jcmeloni-usds** [comment]
Flagging: only you can get to the source data, because Google/WHIT

**Comment by kaschm-usds** [comment]
@jcmeloni-usds fair point. Do you know whether we have access to any mailing list management systems (e.g. Mailchimp, etc)? Happy to move it into an OMB-accessible system if you point me in the right direction.

**Comment by jcmeloni-usds** [comment]
@kaschm-usds I would recommend a GSA mailing list especially for long-term use and not being tied to usds.gov.  @ju-liem do you want to handle owning this, please?  Instructions: https://github.com/usds/usds/blob/master/how-to/mailing-lists-gsa.md (feel free to update those instructions, too, if you run into issues).

**Comment by kaschm-usds** [comment]
@ju-liem happy to help input the folks already on the list once it's up and running! just ping me.

**Comment by ju-liem** [comment]
@kaschm-usds I've put in the request with GSA. I'll let you know when it's been set up.

**Comment by jcmeloni-usds** [comment]
@ju-liem How's this going?

**Comment by ju-liem** [comment]
The list has been created. Handing off to @fatimanoorva to get move the addresses over into the subscription list.

**Comment by fatimanoorva** [comment]
Closing this now as this list has been added to our new mailing list and folks are invited to join our first contributor call on 7/26.
