### ISSUE TITLE
Forms Library Documentation -- ui component props

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#5]
## Problem
`ui:description` and `ui:title` both accept props, but it's undocumented what these props are.

## Acceptance Criteria
- [ ] Documentation is made for the props these (and similar?) components receive

**Comment by jcmeloni-usds** [comment]
Just confirming that I was tripped up by what these do, so I just filled them both in.  I can assume that they populate different attributes of the resulting input field, but that might not be true!

**Comment by bernars-usa** [comment]
Have we handled this, or do we need some additional docs?

**Comment by annekainicUSDS** [comment]
Yes I think this is handled!

**Comment by bernars-usa** [comment]
🎉
