### ISSUE TITLE
Remove Foundation classes from USFS when USWDS 2.0 is released

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#57]
Now that new version of USWDS will soon include more grid support, go back through and remove Foundation classes.

**Comment by jcmeloni-usds** [comment]
This will be amazing.  

I think this should warrant a specific note in a "known issues" or "important upcoming changes" or some such for public consumption -- what do you think @ju-liem ?

**Comment by jcmeloni-usds** [comment]
@ju-liem Let's ensure that the current state of this is documented in the wiki as a known issue/dependency that we're prioritizing removing as soon as we can -- and if we know when that will be because USWDS tells us, let's include that!  Might just ask them.

**Comment by annekainicUSDS** [comment]
This is blocked until USWDS releases version 2.0, because that will provide the grid support we need and currently import from Foundation.

**Comment by annekainicUSDS** [comment]
@jcmeloni-usds I don't have any more updated information, last I heard it was still being worked out, but I haven't heard a release date yet.

**Comment by jcmeloni-usds** [comment]
Ok thanks!

**Comment by jcmeloni-usds** [comment]
Let's not forget this!

**Comment by dmethvin-gov** [comment]
This is most likely to occur as part of #66, since it would be a breaking change for anyone using the library currently.
