### ISSUE TITLE
Issues from prototype walkthrough of N-565

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#6]
From meeting with @sharmaneil @ButtersUSDS
                                              
Issues raised:
1. Lack of consistency with step numbers and pages you have to go through (e.g., the form will say step 2 of 4, but then you go through multiple pages within step 2 of 4; you might think that as soon as you're done with a page that has 2 of 4 at the top that clicking next would take you to step 3 of 4)
2. Navigation: should the top progressbar also serve as navigation? How would you be able to jump around?
3. Moving personal information to the end of the form
4. Answer questions around what is permissible in terms of changing language, moving fields around, removing unnecessary fields, requiring necessary fields, etc.

**Comment by jcmeloni-usds** [comment]
@annekainicUSDS Would it make sense for one of us to break this out into separate issues for better tracking?

**Comment by jcmeloni-usds** [comment]
Assigning to @ju-liem to review.  For each:
* determine to do or not to do
* if not to do, note why
* if to do, create ticket w/ description and acceptance criteria, then prioritize in eng backlog.
* close this when all are addressed in new tickets or wont-fix determinations

**Comment by jcmeloni-usds** [comment]
Closing, because:
* age of issue
* DHS team isn't using forms system
* if DHS team was using forms system, questions  1,2,4 are about understanding the library and question 3 is about the content of the form itself.
