### ISSUE TITLE
Document basic getting started steps

### ISSUE THREAD

**Issue by jcmeloni-usds** [usds/us-forms-system#61]
*Audience* 
* Assume a developer who is familiar with cli and troubleshooting

*Depth*
* For first iteration, something as basic as Mozilla's installation steps (https://github.com/mozilla-services/react-jsonschema-form#installation) is totally fine.

*Success Criteria*
* A person following the instructions can:
  * Install React & USFS library (& other dependencies) locally
  * Run any built-in tests locally
  * Initialize a form on localhost
  * Render form on localhost

*Review Process*
* Assign the issue to @jcmeloni-usds when steps are written and she will follow them as a test!

**Comment by annekainicUSDS** [comment]
Issues that have arisen:

- peer dependencies need to be manually installed
- node modules required by us-forms-system aren't installed when us-forms-system is installed, why is that?

**Comment by annekainicUSDS** [comment]
Getting started instructions here: https://github.com/usds/us-forms-system/blob/master/docs/getting-started.md.

Also fixed the above issues related to dependencies.

**Comment by annekainicUSDS** [comment]
@jcmeloni-usds @ju-liem I'm waiting to close this until I get the approval from you guys in testing what I've put together that everything looks good!

**Comment by jcmeloni-usds** [comment]
@annekainicUSDS Confirmed the starter app is good to go - I had to fiddle a little with node on my ubuntu system but that's just because of what'ls in the standard ubuntu install (4.x).  Once I got the versions settled out, it works like a charm. We'll iterate on doc'n as we move on but I am COMPLETELY HAPPY with closing this as good to go for the present state of play.

:tada: :tada: :tada:

**Comment by annekainicUSDS** [comment]
Awesome!
