### ISSUE TITLE
Feature Requests / Clarifications from the USDS @ DHS Team 

### ISSUE THREAD

**Issue by kaschm-usds** [usds/us-forms-system#70]
We are building a prototype using the US Forms System for the USCIS Fee Waiver (I-912) Form. There are a few features that we'll need from either USFS code or that we can custom-create. I've transfered info from out email exchange below so we can sort it all out. 

NB: @ju-liem - not sure how to label this. Halp! 

## Feature Needs: 

1. **Ability to "Add More"** - there is already a feature where you can add more of a type in the library, but it doesn't currently work for text fields. We'll play around with this. 
2. **Tally over specific fields** - per conversation, this might have to be a separate function that runs on the config to gather that info before submitting. Currently, USFS has a function that transforms the config into data for submission, so the custom function might happen at this stage.
3. **Link to external page in instructions** - Need to be able to launch a page via the Instructions. Sounds like the way to do this is via the existing feature to add custom content wherever you need in the config. Potential solution: create a custom component that would include explanatory text and a link to a separate page, and render that from the config.
4.  **Upload Documents** - I-912 requires requestor upload supporting materials in many sections. There is already a feature in discovery - tracking [here](https://github.com/usds/us-forms-system/issues/52) 
5.  **State Dropdown** - Sounds like there is already a State option in the library. We'll see whether this works for our purposes!
6.  **Read-only Review Page** - Post-form completion, we'd like the ability to review information gathered in a read-only way. Does this already exist? @annekainicUSDS is confirming. 
7.  **Download Documents** - third party signers will need to download an (empty) form, fill it out, sign it, and upload it. Note for @sharmaneil  - If we can populate this PDF with json blob info first, that would be amazing, but not required. 

cc/ @benwarfield-usds @mlighdc @iamandrewmiller-usds

**Comment by kaschm-usds** [comment]
@annekainicUSDS - Talked to DHS folks about e-signature requirements. Looks like we need four components: 

1. Download PDF [**now reflected in #7 in main issue**] 
2. Upload PDF [already reflected in #4] 
3. Checkbox [ok!] 
4. Conditional text field [ok!] 

Thanks!

**Comment by ju-liem** [comment]
@kaschm-usds Let's talk about the Download Documents functionality. Pinging you now about it.

**Comment by jcmeloni-usds** [comment]
Some of these may end up being outside the bounds of the USFS and have to do with construction of the app around the form, so def we need to discuss and then break this list into actionable issues when they're determined to be actionable.

**Comment by ju-liem** [comment]
Closing. All of the requested capabilities in this issue are either already accounted for in some way, or exist in another way within the library.
