### ISSUE TITLE
Create a User-Centered Visual PRA Guide

### ISSUE THREAD

**Issue by ButtersUSDS** [usds/us-forms-system#78]
- [ ] Cans and Can'ts with visual examples

- [ ] Can'ts are actually Cans with PRA review implications. Those should be explained.

- [ ] Crowdsource Design CoP

- [ ] Include PRA reference links where applicable

- [ ] Work with Andrew Hughey to make sure the guide is true

**Comment by jcmeloni-usds** [comment]
Labelling this as wont-fix and closing.  Am creating a new issue about offering PRA guidance in the wiki.
