### ISSUE TITLE
How to deal with browser prefixes in USWDS

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#80]
I've discovered an issue in how we're importing USWDS. In one of their stylesheets, they [recently](https://github.com/uswds/uswds/pull/2356) removed vendor prefixes for a particular style that hides the default styling for a select field. Even though USWDS is using autoprefixer, it only applies the autoprefixer after compiling the stylesheets into css. Because we are using the sass files directly, we aren't getting the browser prefixes, creating the following UI bug:

<img width="513" alt="screen shot 2018-06-14 at 5 44 02 pm" src="https://user-images.githubusercontent.com/25183456/41440043-0576b510-6ffb-11e8-8bad-e33df536eb5a.png">

I believe there are a couple of viable options to fixing this bug:
1. Instead of importing individual sass files from USWDS, import the compiled css file. The downside of this approach is that it includes a lot more styles than we actually need (right now we're importing only the specific sass files we need from USWDS).
2. Include [autoprefixer](https://github.com/postcss/autoprefixer) on our side. There are 2 ways we can include autoprefixer. The first is we can use webpack in us-forms-system-starter-app, which would not include those prefixes here, so if someone is installing us-forms-system directly they wouldn't benefit from that change. We could also use the CLI version of autoprefixer during the build step within us-forms-system.

I'm inclined to go with option 2 (using the CLI version specifically), but curious to get thoughts on this. @jordangov or @jcmeloni-usds have thoughts?

**Comment by jordangov** [comment]
I'm also inclined to go with option 2. Although implementing through CLI directly now might work, as we add steps (eventually) we may need to add a simple build system.

**Comment by jordangov** [comment]
Specifically, I mean adding all the various steps into one unified build process.

**Comment by nacingov** [comment]
It makes the most sense to me for the downstream project to do its own autoprefixing, at least as long as it is acceptable to the upstream project to use the Sass files directly (and I assume it is).

**Comment by annekainicUSDS** [comment]
Interesting, thanks for the feedback @nacingov. I wasn't sure what the best practice is related to what you can expect users of your library to have configured on their side. In general I think we've tried to assume as little as possible about what downstream projects will need in order for things to work properly. For example, we transpile ES6 on our side, we compile the sass into css on our side, etc.

I'd love to have a more general conversation about the best strategy for building an open source library such as this and what you should build into your library vs. what you should expect downstream users to have set up on their side. It's hard to know what to build into this library because we don't have a ton of users yet (1.5 right now), so we don't yet know a lot about how this library is going to be used and in what environments it's going to be installed.

**Comment by nacingov** [comment]
Ah, I'm sorry, that was inarticulately worded. I was referring to the forms system _being_ the downstream project! (But it also could conceivably be the project downstream from the forms system that might want to change how the autoprefixing is set up, because they want a wider or narrower set of browsers.)

@dmethvin-gov, what do you think?

**Comment by dmethvin-gov** [comment]
If people are allowed to include the USWDS sass files then it seems like we'll need to auto prefix on our (end-developer project) side. I think it's good for us to do that anyway since we may need prefixed properties ourselves.

**Comment by annekainicUSDS** [comment]
Sounds great! Thanks for the input @dmethvin-gov. I've added that in [this PR](https://github.com/usds/us-forms-system/pull/81) so I think this ticket can be closed. Thanks for weighing in everyone!
