### ISSUE TITLE
Review GitHub settings

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#85]
There are a lot of GitHub settings that we haven't totally configured that we should probably look into. For example, should we require reviews before merging PRs? Should we enable status checks? Should we include some kind of "build passing" stamp with the repo? What else would we want to make sure is in place in order for the repo to be secure?

**Comment by annekainicUSDS** [comment]
I'm requiring reviews before merging PRs for now. I hadn't included this up until this point because I was the only engineer working on the project, but now that we have another person to push and review code I think this makes sense!

**Comment by jcmeloni-usds** [comment]
My thoughts:
* yes on reviews
* yes on anything linty you want to add in
* would love to throw code climate on it (free for open source)
* I looooove me some hooks so go nuts :)

**Comment by dmethvin-gov** [comment]
SGTM too! Reviews for anything code-wise is very helpful, although trivial changes may not warrant bothering someone. Usually the social stigma of a **ಠ_ಠ** from peers will prevent us from abusing the exceptions.

**Comment by dmethvin-gov** [comment]
The team all has access to the Settings tab now, thanks @annekainicUSDS! I took a look at the settings and they look good to me. We can always tweak them if needed so I'll close this ticket.
