### ISSUE TITLE
Organize docs in docs folder

### ISSUE THREAD

**Issue by bernars-usa** [usds/us-forms-system#86]
The documentation in https://github.com/usds/us-forms-system/tree/master/docs is accurate (according to people in our kickoff meeting!), but now needs some organization, such as some directory-level README.md files for navigation, and likely breaking up some information into separate files.

I'll read through what exists and put together an outline, solicit feedback on the organization, then open some PRs. 📚 

cc @usds/forms-system

**Comment by bernars-usa** [comment]
Here's a first crack at an outline based on what I've found in https://github.com/usds/us-forms-system/tree/master/docs. I'm likely mixing up terminology or order of importance... just point it out and I'll move/fix.

🗺 denotes a "map topic", which is a high-level conceptual topic that collects related topics together.

| Topic Title | Source |
|---|---|
| 🗺**Getting Started with the Forms System Library** | [getting-started.md](https://github.com/usds/us-forms-system/blob/master/docs/getting-started.md)  |
| Creating a new application with the US Forms System Starter App | [getting-started.md#1-start-a-new-application](https://github.com/usds/us-forms-system/blob/master/docs/getting-started.md#1-start-a-new-application) |
| Installing the library in an existing application | [getting-started.md#2-install-in-an-existing-application](https://github.com/usds/us-forms-system/blob/master/docs/getting-started.md#2-install-in-an-existing-application) |
| 🗺**Building a form** | NA |
| About the JSON schema standard and react-jsonschema-form | [walkthrough.md#json-schema](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/walkthrough.md#json-schema), [walkthrough.md#how-react-jsonschema-form-works](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/walkthrough.md#how-react-jsonschema-form-works) |
| Creating a form config file | [form-config.md#form-config](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/form-config.md#form-config), [form-config.md#uischema-configuration](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/form-config.md#uischema-configuration) |
| Adding widgets | [field-library.md#widgets](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/field-library.md#widgets) |
| Adding widget definitions | [field-library.md#definitions](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/field-library.md#definitions) |
| Creating custom widgets | [walkthrough.md#customization](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/walkthrough.md#customization), [form-config.md#uischema-configuration](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/form-config.md#uischema-configuration) |
| Creating multi-page forms | [walkthrough.md#multi-page-forms](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/walkthrough.md#multi-page-forms) |
| 🗺**Form recipes** | [form-config.md#schemaform-cookbook](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/form-config.md#schemaform-cookbook) |
| Writing custom field validation | [form-config.md#i-need-to-write-custom-validation](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/form-config.md#i-need-to-write-custom-validation) |
| Validating a field based on other fields in the same object | [form-config.md#i-need-to-validate-a-field-based-on-other-fields-in-the-same-object](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/form-config.md#i-need-to-validate-a-field-based-on-other-fields-in-the-same-object) |
| Changing drop-down options based on data in another field | [form-config.md#i-want-to-change-the-options-of-a-dropdown-based-on-some-other-field-data](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/form-config.md#i-want-to-change-the-options-of-a-dropdown-based-on-some-other-field-data) |
| Creating a block of text with no associated fields | [form-config.md#i-want-to-show-a-block-of-text-without-any-fields](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/form-config.md#i-want-to-show-a-block-of-text-without-any-fields) |
| Conditionally hiding a group of fields | [form-config.md#i-want-to-conditionally-hide-a-group-of-fields](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/form-config.md#i-want-to-conditionally-hide-a-group-of-fields) |
| Styling expanded or collapsed fields | [form-config.md#i-want-to-indent-or-style-the-fields-that-are-using-expandunder](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/form-config.md#i-want-to-indent-or-style-the-fields-that-are-using-expandunder) |
| Conditionally including a page | [form-config.md#i-want-to-skip--conditionally-include-a-page-based-on-some-information](https://github.com/usds/us-forms-system/blob/master/docs/How%20the%20library%20works/form-config.md#i-want-to-skip--conditionally-include-a-page-based-on-some-information) |

**Comment by bernars-usa** [comment]
WIP PR opened in #90.

**Comment by annekainicUSDS** [comment]
The outline looks great! In looking through some of the docs I'm noticing a bunch of things that need updating, but we can dig into the content once they are reorganized.

**Comment by bernars-usa** [comment]
> I'm noticing a bunch of things that need updating, but we can dig into the content once they are reorganized.

Definitely. 👍 Thanks for reviewing, @annekainicUSDS!

**Comment by bernars-usa** [comment]
Getting Started content PR is ready for review: https://github.com/usds/us-forms-system/pull/96.
