### ISSUE TITLE
How should people use the starter app?

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#87]
1. Clone or fork?
2. Where is it going to be used? In an existing project? As the beginning of a new project?

**Comment by jcmeloni-usds** [comment]
My votes:
1) clone
2) I would imagine this answer leans toward beginning of a new project, because if it's part of an existing project the dev is more likely to have all the scaffolding built up and ready to drop a new react-based form into an existing place.

**Comment by dmethvin-gov** [comment]
I agree with that. At some point we might also want to create a more advanced example that shows how to accomplish the things in the how-do-I docs, especially if they involve external components.

**Comment by annekainicUSDS** [comment]
@bernars-usa here's a ticket for the conversation we're having about cloning or forking the starter app. We can document discussions around that in here!

**Comment by bernars-usa** [comment]
Oh perfect! I'm currently documenting cloning rather than forking per our conversation this morning. Will push up 🔜.

**Comment by bernars-usa** [comment]
Here's where the first draft of the setup doc ended up: https://github.com/usds/us-forms-system/blob/getting-started/docs/getting-started/creating-a-new-application-with-the-us-forms-system-starter-app.md#clone-the-starter-app-repository-and-change-the-remote-url

**Comment by annekainicUSDS** [comment]
I think this is good for now! We can gather feedback at the hackathon to see if our suggested approach works. Closing.
