### ISSUE TITLE
Issues identified in porting code to new repo

### ISSUE THREAD

**Issue by annekainicUSDS** [usds/us-forms-system#9]
1. `environment.js` has vets.gov-specific logic. Might need to create a separate config file for this information that a user will have to specify in setup.
  --> new ticket: https://github.com/usds/us-forms-system/issues/50
2. What to do about the `nonMilitaryJobs` definition (it imports an education-specific component)
  --> new ticket: https://github.com/usds/us-forms-system/issues/51
3. What to do about `PrivacyAgreement` component
  --> new ticket: https://github.com/usds/us-forms-system/issues/53
4. Figure out how to port over this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/7334/files
  --> no longer necessary because this is only used as part of the save in progress code, which we have extracted out of the library
5. FileField doesn't return the response as expected. Look into FileField behavior and how it interacts with the server.
  --> new ticket: https://github.com/usds/us-forms-system/issues/52

**Comment by ju-liem** [comment]
After investigating each, new tickets for needed work should be created.

**Comment by annekainicUSDS** [comment]
Investigated each of the items above and have created new tickets for them (see description for new ticket links). Closing as this is no longer needed.
