### ISSUE TITLE
Prep for Form-a-polooza (June 30)

### ISSUE THREAD

**Issue by fatimanoorva** [usds/us-forms-system#93]
- What are we hoping to get out of this event?
- What open tickets do we want to prioritize?
- What assets/materials would we like to bring/develop in advance (demo/pitch deck, 1-pagers, stickers, etc.)
- Do we need time on the event agenda? (here is the current draft: https://formapalooza.dc.gov/agenda/)

_feel free to reference existing tickets below_

**Comment by dmethvin-gov** [comment]
Maybe we could build one of the forms in the agenda using the forms system, and get feedback based on it? That way we wouldn't be encouraging people to start using it in its current form but we could get important information about how they might use it once we do. I suspect their feature needs will be similar to the ones we've already identified, like custom themes and field values/constraints based on other field values.

**Comment by fatimanoorva** [comment]
@dmethvin-gov Agree! I think Anne was to going to look into the DC forms and see if we could possibly pick one to test out. 

BTW, here are the list of forms:

1. [DC Public School Enrollment Packet](https://dcps.dc.gov/sites/default/files/dc/sites/dcps/publication/attachments/SY%2017-18%20Full%20Enrollment%20Packet%20Medical%20Docs%20Disclosures.pdf)
1. [Child Care Subsidy Application](https://static1.squarespace.com/static/5a99ca5ae17ba3a8b20c8d8c/t/5af7692d88251bace41d4f7b/1526163764402/Application+for+Child+Care+Services.pdf)
1. [Certificate of Occupancy](https://dcra.dc.gov/sites/default/files/dc/sites/dcra/publication/attachments/certificate_of_occupancy_application.pdf)
1. [Food Truck Health Certificate Application](https://doh.dc.gov/sites/default/files/dc/sites/doh/publication/attachments/Vending%20Application%20-%20Form%20A.pdf)
1. [Disability Parking Space & Placard Application](https://ddot.dc.gov/sites/default/files/dc/sites/ddot/publication/attachments/ADA%20New%20and%20Renewal%20Application_1.pdf)

**Comment by fatimanoorva** [comment]
Per conversation with @ju-liem, we will try not to divert too much from their format and set agenda. If possible, we can try to prototype one of their forms using the forms system during one of the breakouts. Otherwise, we will participate normally / be "flies in the wall". Will go ahead and close this one out for now!
